<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Ml_governance extends Authorized_Controller
{
	protected $required_permission='ml.view';
	public function __construct(){parent::__construct();$this->load->model('Ml_governance_model');$this->load->library('form_validation');}
	public function index(){$this->render('ml_governance/index',array('page_title'=>'ML Governance','page_subtitle'=>'Immutable datasets, reviewed labels, asynchronous exports, and registry metadata','datasets'=>$this->Ml_governance_model->datasets(),'jobs'=>$this->Ml_governance_model->jobs(),'models'=>$this->Ml_governance_model->models(),'can_train'=>in_array('ml.train',$this->current_permissions,TRUE),'page_styles'=>array('assets/plugins/datatables/css/dataTables.bootstrap5.min.css'),'page_scripts'=>array('assets/plugins/datatables/js/dataTables.min.js','assets/plugins/datatables/js/dataTables.bootstrap5.min.js','assets/js/modules/master-data.js'),'breadcrumbs'=>array(array('label'=>'ML Governance'))));}
	public function create_dataset(){$this->authorize('ml.train');$error=NULL;$this->form_validation->set_rules('dataset_code','Dataset code','trim|required|max_length[50]|regex_match[/^[A-Za-z][A-Za-z0-9_-]{2,49}$/]');$this->form_validation->set_rules('dataset_name','Dataset name','trim|required|max_length[200]');$this->form_validation->set_rules('capability','Capability','trim|required|in_list[EXTRACTION,MAPPING,RESOURCE_TEMPLATE]');$this->form_validation->set_rules('description','Description','trim|max_length[1000]');if($this->input->method(TRUE)==='POST'&&$this->form_validation->run()){$code=strtoupper(trim((string)$this->input->post('dataset_code',TRUE)));if($this->Ml_governance_model->code_exists($code))$error='That dataset code already exists.';else{$id=$this->Ml_governance_model->create_dataset(array('dataset_code'=>$code,'dataset_name'=>trim((string)$this->input->post('dataset_name',TRUE)),'capability'=>$this->input->post('capability',TRUE),'description'=>$this->nullable('description'),'created_by'=>$this->current_user->user_id));if($id){$this->session->set_flashdata('ml_success','Dataset created.');redirect('ml-governance/datasets/'.$id);}$error='Unable to create the dataset.';}}$this->render('ml_governance/dataset_form',array('page_title'=>'Create ML Dataset','page_subtitle'=>'Define a governed snapshot source','form_error'=>$error,'breadcrumbs'=>array(array('label'=>'ML Governance','url'=>site_url('ml-governance')),array('label'=>'Create Dataset'))));}
	public function dataset($id){$d=$this->Ml_governance_model->find_dataset($id);if(!$d)show_404();$this->render('ml_governance/dataset',array('page_title'=>$d->dataset_code,'page_subtitle'=>$d->dataset_name,'dataset'=>$d,'versions'=>$this->Ml_governance_model->versions($id),'can_train'=>in_array('ml.train',$this->current_permissions,TRUE),'breadcrumbs'=>array(array('label'=>'ML Governance','url'=>site_url('ml-governance')),array('label'=>$d->dataset_code))));}
	public function create_version($id){$this->authorize('ml.train');if($this->input->method(TRUE)!=='POST')show_error('Method Not Allowed',405);$d=$this->Ml_governance_model->find_dataset($id);if(!$d)show_404();$result=$this->Ml_governance_model->create_version($id,$this->nullable('notes'),$this->current_user->user_id);if(!empty($result['error'])){$this->session->set_flashdata('ml_error',$result['error']);redirect('ml-governance/datasets/'.$id);}$this->session->set_flashdata('ml_success','Draft version created with '.$result['record_count'].' immutable source snapshot(s).');redirect('ml-governance/versions/'.$result['dataset_version_id']);}
	public function version($id){$v=$this->Ml_governance_model->find_version($id);if(!$v)show_404();$this->render('ml_governance/version',array('page_title'=>$v->dataset_code.' v'.$v->version_no,'page_subtitle'=>'Dataset version and label review','version'=>$v,'records'=>$this->Ml_governance_model->records($id),'counts'=>$this->Ml_governance_model->record_counts($id),'feedback'=>$this->Ml_governance_model->feedback($id),'can_review'=>in_array('ml.review',$this->current_permissions,TRUE),'can_train'=>in_array('ml.train',$this->current_permissions,TRUE),'breadcrumbs'=>array(array('label'=>'ML Governance','url'=>site_url('ml-governance')),array('label'=>$v->dataset_code,'url'=>site_url('ml-governance/datasets/'.$v->dataset_id)),array('label'=>'v'.$v->version_no))));}
	public function review($version_id,$record_id){$this->authorize('ml.review');if($this->input->method(TRUE)!=='POST')show_error('Method Not Allowed',405);$status=strtoupper(trim((string)$this->input->post('label_status',TRUE)));$comments=$this->nullable('comments');if(!in_array($status,array('APPROVED','REJECTED','PENDING'),TRUE)||!$this->Ml_governance_model->review_record($record_id,$status,$comments,$this->current_user->user_id))$this->session->set_flashdata('ml_error','The label could not be reviewed; only Draft version labels are mutable.');else$this->session->set_flashdata('ml_success','Label review recorded in append-only feedback history.');redirect('ml-governance/versions/'.$version_id);}
	public function freeze($id){$this->authorize('ml.train');if($this->input->method(TRUE)!=='POST')show_error('Method Not Allowed',405);$result=$this->Ml_governance_model->freeze($id,$this->current_user->user_id);$this->session->set_flashdata(empty($result['error'])?'ml_success':'ml_error',empty($result['error'])?'Version frozen and export job queued.':$result['error']);redirect('ml-governance/versions/'.$id);}
	public function approve($id){$this->authorize('ml.review');if($this->input->method(TRUE)!=='POST')show_error('Method Not Allowed',405);$ok=$this->Ml_governance_model->approve($id,$this->current_user->user_id);$this->session->set_flashdata($ok?'ml_success':'ml_error',$ok?'Dataset version approved and immutable.':'A successful checksum-verified export is required before approval.');redirect('ml-governance/versions/'.$id);}
	private function nullable($field){$v=trim((string)$this->input->post($field,TRUE));return$v===''?NULL:$v;}
}
