<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Rates extends Authorized_Controller
{
	protected $required_permission='rates.view';
	private $types=array('material','labor','cost_item');
	public function __construct(){parent::__construct();$this->load->model('Rate_model');$this->load->library('form_validation');}
	public function index(){$this->render('rates/index',array('page_title'=>'Rate Management and History','page_subtitle'=>'Current governed rates, effective schedules, historical observations, and source context','current_material'=>$this->Rate_model->current_material_rates(),'material_history'=>$this->Rate_model->material_history(),'current_labor'=>$this->Rate_model->current_labor_rates(),'labor_history'=>$this->Rate_model->labor_history(),'cost_item_history'=>$this->Rate_model->cost_item_history(),'can_manage'=>in_array('rates.manage',$this->current_permissions,TRUE),'page_styles'=>array('assets/plugins/datatables/css/dataTables.bootstrap5.min.css'),'page_scripts'=>array('assets/plugins/datatables/js/dataTables.min.js','assets/plugins/datatables/js/dataTables.bootstrap5.min.js','assets/js/modules/master-data.js'),'breadcrumbs'=>array(array('label'=>'Rate Management and History'))));}

	public function create($type)
	{
		$this->authorize('rates.manage');$type=$this->valid_type($type);$form_error=NULL;$this->set_rules($type);
		if($this->input->method(TRUE)==='POST'&&$this->form_validation->run()){
			if($type==='cost_item'){$data=$this->cost_item_data();$refs=array('project_id'=>array('project_master','project_id'),'rate_source_type_id'=>array('ref_rate_source_type','rate_source_type_id'),'rate_basis_id'=>array('ref_rate_basis','rate_basis_id'),'price_period_id'=>array('ref_price_period','price_period_id'),'location_id'=>array('ref_location','location_id'));if(!$this->Rate_model->exists('standard_cost_item_revision','cost_item_revision_id',$data['cost_item_revision_id']))$form_error='The selected standard cost item revision is invalid.';else foreach($refs as$field=>$ref)if($data[$field]!==NULL&&!$this->Rate_model->exists($ref[0],$ref[1],$data[$field])){$form_error='One or more selected rate references are invalid.';break;}if($form_error===NULL){if($this->Rate_model->append_cost_item($data)){$this->session->set_flashdata('rate_success','Cost-item rate observation appended successfully.');redirect('rates');}$form_error='Unable to append the rate observation.';}}
			else{$schedule=$this->schedule_data($type);if($schedule['location_id']!==NULL&&!$this->Rate_model->exists('ref_location','location_id',$schedule['location_id']))$form_error='The selected schedule location is invalid.';elseif($this->Rate_model->schedule_code_exists($type,$schedule['schedule_code']))$form_error='That schedule code already exists.';elseif($schedule['effective_to']&&$schedule['effective_to']<$schedule['effective_from'])$form_error='Effective To cannot be earlier than Effective From.';else{$rate=$type==='material'?$this->material_data():$this->labor_data();$table=$type==='material'?'material_variant':'labor_master';$key=$type==='material'?'material_variant_id':'labor_id';if(!$this->Rate_model->exists($table,$key,$rate[$key]))$form_error='The selected resource is invalid.';elseif(($type==='material'?$this->Rate_model->append_material($schedule,$rate):$this->Rate_model->append_labor($schedule,$rate))){$this->session->set_flashdata('rate_success',ucfirst($type).' rate appended successfully. Prior history was preserved.');redirect('rates');}else$form_error='Unable to append the rate.';}}
		}
		$this->render('rates/form',array('page_title'=>'Append '.($type==='cost_item'?'Cost Item':ucfirst($type)).' Rate','page_subtitle'=>'Historical records are immutable','type'=>$type,'resource_options'=>$this->Rate_model->options($type),'projects'=>$this->Rate_model->projects(),'locations'=>$this->Rate_model->reference_options('ref_location','location_id','psgc_code','location_name'),'source_types'=>$this->Rate_model->reference_options('ref_rate_source_type','rate_source_type_id','source_type_code','source_type_name'),'rate_bases'=>$this->Rate_model->reference_options('ref_rate_basis','rate_basis_id','rate_basis_code','rate_basis_name'),'price_periods'=>$this->Rate_model->reference_options('ref_price_period','price_period_id','period_code','period_label'),'form_error'=>$form_error,'breadcrumbs'=>array(array('label'=>'Rate Management and History','url'=>site_url('rates')),array('label'=>'Append Rate'))));
	}

	private function set_rules($type)
	{
		if($type==='cost_item'){foreach(array('cost_item_revision_id'=>'Standard cost item','rate_type'=>'Rate type','unit_rate'=>'Unit rate','currency_code'=>'Currency')as$f=>$l)$this->form_validation->set_rules($f,$l,'trim|required'.($f==='cost_item_revision_id'?'|integer':($f==='unit_rate'?'|numeric|greater_than_equal_to[0]':'|max_length[50]')));$this->form_validation->set_rules('quantity','Quantity','trim|numeric|greater_than_equal_to[0]');foreach(array('project_id'=>'Project','rate_source_type_id'=>'Source type','rate_basis_id'=>'Rate basis','price_period_id'=>'Price period','location_id'=>'Location')as$f=>$l)$this->form_validation->set_rules($f,$l,'trim|integer');$this->form_validation->set_rules('rate_date','Rate date','trim|regex_match[/^\d{4}-\d{2}-\d{2}$/]');foreach(array('city'=>100,'province'=>100,'region'=>100,'source_system'=>100,'source_document'=>255,'source_record_key'=>255,'contractor_supplier'=>255)as$f=>$max)$this->form_validation->set_rules($f,ucwords(str_replace('_',' ',$f)),'trim|max_length['.$max.']');return;}
		$key=$type==='material'?'material_variant_id':'labor_id';$this->form_validation->set_rules($key,'Resource','trim|required|integer');$this->form_validation->set_rules('location_id','Location','trim|integer');$this->form_validation->set_rules('schedule_code','Schedule code','trim|required|max_length[50]');$this->form_validation->set_rules('schedule_name','Schedule name','trim|required|max_length[200]');$this->form_validation->set_rules('currency_code','Currency','trim|required|max_length[10]');$this->form_validation->set_rules('effective_from','Effective From','trim|required|regex_match[/^\d{4}-\d{2}-\d{2}$/]');$this->form_validation->set_rules('effective_to','Effective To','trim|regex_match[/^\d{4}-\d{2}-\d{2}$/]');$this->form_validation->set_rules('rate_status','Rate status','trim|required|max_length[50]');if($type==='material')$this->form_validation->set_rules('unit_rate','Unit rate','trim|required|numeric|greater_than_equal_to[0]');else{foreach(array('basic_daily_rate','basic_monthly_rate','ot_rate_2hrs','daily_rate','total_without_admin_fee','total_with_admin_fee','admin_fee_percentage')as$f)$this->form_validation->set_rules($f,ucwords(str_replace('_',' ',$f)),'trim|required|numeric|greater_than_equal_to[0]');$this->form_validation->set_rules('source_reference','Source reference','trim|max_length[255]');$this->form_validation->set_rules('source_status','Source status','trim|max_length[50]');}
	}
	private function schedule_data($type){$data=array('schedule_code'=>strtoupper(trim((string)$this->input->post('schedule_code',TRUE))),'schedule_name'=>trim((string)$this->input->post('schedule_name',TRUE)),'currency_code'=>strtoupper(trim((string)$this->input->post('currency_code',TRUE))),'location_id'=>$this->nullable_id('location_id'),'effective_from'=>$this->nullable('effective_from'),'effective_to'=>$this->nullable('effective_to'),'is_active'=>1);if($type==='labor')$data+=array('admin_fee_percentage'=>(float)$this->input->post('admin_fee_percentage'),'source_status'=>$this->nullable('source_status'),'notes'=>$this->nullable('notes'));return$data;}
	private function material_data(){return array('material_variant_id'=>(int)$this->input->post('material_variant_id'),'unit_rate'=>(float)$this->input->post('unit_rate'),'rate_status'=>strtoupper(trim((string)$this->input->post('rate_status',TRUE))),'is_current'=>1);}
	private function labor_data(){return array('labor_id'=>(int)$this->input->post('labor_id'),'basic_daily_rate'=>(float)$this->input->post('basic_daily_rate'),'basic_monthly_rate'=>(float)$this->input->post('basic_monthly_rate'),'ot_rate_2hrs'=>(float)$this->input->post('ot_rate_2hrs'),'daily_rate'=>(float)$this->input->post('daily_rate'),'total_without_admin_fee'=>(float)$this->input->post('total_without_admin_fee'),'total_with_admin_fee'=>(float)$this->input->post('total_with_admin_fee'),'source_reference'=>$this->nullable('source_reference'),'rate_status'=>strtoupper(trim((string)$this->input->post('rate_status',TRUE))),'is_current'=>1);}
	private function cost_item_data(){return array('cost_item_revision_id'=>(int)$this->input->post('cost_item_revision_id'),'project_id'=>$this->nullable_id('project_id'),'rate_type'=>strtoupper(trim((string)$this->input->post('rate_type',TRUE))),'rate_source_type_id'=>$this->nullable_id('rate_source_type_id'),'rate_basis_id'=>$this->nullable_id('rate_basis_id'),'quantity'=>$this->nullable_number('quantity'),'unit_rate'=>(float)$this->input->post('unit_rate'),'currency_code'=>strtoupper(trim((string)$this->input->post('currency_code',TRUE))),'rate_date'=>$this->nullable('rate_date'),'price_period_id'=>$this->nullable_id('price_period_id'),'location_id'=>$this->nullable_id('location_id'),'city'=>$this->nullable('city'),'province'=>$this->nullable('province'),'region'=>$this->nullable('region'),'source_system'=>$this->nullable('source_system'),'source_document'=>$this->nullable('source_document'),'source_record_key'=>$this->nullable('source_record_key'),'contractor_supplier'=>$this->nullable('contractor_supplier'),'is_validated'=>0,'validation_status'=>'PENDING','validation_status_id'=>$this->Rate_model->pending_validation_status_id());}
	private function valid_type($type){if(!in_array($type,$this->types,TRUE))show_404();return$type;}
	private function nullable($field){$v=trim((string)$this->input->post($field,TRUE));return$v===''?NULL:$v;}
	private function nullable_id($field){$v=$this->nullable($field);return$v===NULL?NULL:(int)$v;}
	private function nullable_number($field){$v=$this->nullable($field);return$v===NULL?NULL:(float)$v;}
}
