<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="row justify-content-center"><div class="col-xl-9"><div class="card shadow-sm">
	<div class="card-header"><h2 class="card-title mb-0"><?= html_escape($page_title) ?></h2></div><div class="card-body">
	<?php if ($form_error): ?><div class="alert alert-danger" role="alert"><?= html_escape($form_error) ?></div><?php endif; ?>
	<?= validation_errors('<div class="alert alert-danger" role="alert">', '</div>') ?>
	<?= form_open(current_url(), array('novalidate' => 'novalidate')) ?>
		<div class="row g-3">
			<div class="col-md-4"><label class="form-label" for="material_code">Material code *</label><input class="form-control text-uppercase" id="material_code" name="material_code" maxlength="50" value="<?= set_value('material_code', $material->material_code ?? '') ?>" required></div>
			<div class="col-md-8"><label class="form-label" for="material_name">Material name *</label><input class="form-control" id="material_name" name="material_name" maxlength="255" value="<?= set_value('material_name', $material->material_name ?? '') ?>" required></div>
			<div class="col-md-6"><label class="form-label" for="material_category_id">Category *</label><select class="form-select" id="material_category_id" name="material_category_id" required><option value="">Select…</option><?php foreach ($options['categories'] as $option): ?><option value="<?= (int) $option->option_id ?>" <?= set_select('material_category_id', (string) $option->option_id, (string) set_value('material_category_id', $material->material_category_id ?? '') === (string) $option->option_id) ?>><?= html_escape($option->option_label) ?></option><?php endforeach; ?></select></div>
			<div class="col-md-6"><label class="form-label" for="material_group_id">Material group</label><select class="form-select" id="material_group_id" name="material_group_id"><option value="">None</option><?php foreach ($options['groups'] as $option): ?><option value="<?= (int) $option->option_id ?>" <?= set_select('material_group_id', (string) $option->option_id, (string) set_value('material_group_id', $material->material_group_id ?? '') === (string) $option->option_id) ?>><?= html_escape($option->option_label) ?></option><?php endforeach; ?></select></div>
			<div class="col-md-6"><label class="form-label" for="default_uom_id">Default UOM</label><select class="form-select" id="default_uom_id" name="default_uom_id"><option value="">None</option><?php foreach ($options['uoms'] as $option): ?><option value="<?= (int) $option->option_id ?>" <?= set_select('default_uom_id', (string) $option->option_id, (string) set_value('default_uom_id', $material->default_uom_id ?? '') === (string) $option->option_id) ?>><?= html_escape($option->option_label) ?></option><?php endforeach; ?></select></div>
			<div class="col-md-6"><label class="form-label" for="specification_id">Specification</label><select class="form-select" id="specification_id" name="specification_id"><option value="">None</option><?php foreach ($options['specifications'] as $option): ?><option value="<?= (int) $option->option_id ?>" <?= set_select('specification_id', (string) $option->option_id, (string) set_value('specification_id', $material->specification_id ?? '') === (string) $option->option_id) ?>><?= html_escape($option->option_label) ?></option><?php endforeach; ?></select></div>
			<div class="col-md-6"><label class="form-label" for="attribute_subject_class_id">Attribute subject class</label><select class="form-select" id="attribute_subject_class_id" name="attribute_subject_class_id"><option value="">None</option><?php foreach ($options['attribute_classes'] as $option): ?><option value="<?= (int) $option->option_id ?>" <?= set_select('attribute_subject_class_id', (string) $option->option_id, (string) set_value('attribute_subject_class_id', $material->attribute_subject_class_id ?? '') === (string) $option->option_id) ?>><?= html_escape($option->option_label) ?></option><?php endforeach; ?></select></div>
		</div>
		<?php $active_default = $this->input->method(TRUE) !== 'POST' && ($material === NULL || (bool) $material->is_active); ?>
		<div class="form-check my-4"><input class="form-check-input" type="checkbox" id="is_active" name="is_active" value="1" <?= set_checkbox('is_active', '1', $active_default) ?>><label class="form-check-label" for="is_active">Active</label></div>
		<?php if ($material): ?><p class="small text-body-secondary">Created <?= html_escape(date('d-M-Y h:i A', strtotime($material->created_at))) ?> · Updated <?= html_escape(date('d-M-Y h:i A', strtotime($material->updated_at))) ?></p><?php endif; ?>
		<button class="btn btn-primary" type="submit">Save Material</button> <a class="btn btn-outline-secondary" href="<?= $material ? site_url('materials/'.$material->material_id) : site_url('materials') ?>">Cancel</a>
	<?= form_close() ?>
	</div>
</div></div></div>
