<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<?php if ($this->session->flashdata('material_success')): ?><div class="alert alert-success" role="alert"><?= html_escape($this->session->flashdata('material_success')) ?></div><?php endif; ?>
<div class="d-flex flex-wrap gap-2 mb-3"><?php if ($can_manage): ?><a class="btn btn-primary" href="<?= site_url('materials/'.$material->material_id.'/edit') ?>"><i class="bi bi-pencil" aria-hidden="true"></i> Edit Material</a><?= form_open('materials/'.$material->material_id.'/status', array('class' => 'd-inline')) ?><button class="btn btn-outline-<?= $material->is_active ? 'danger' : 'success' ?>" type="submit"><?= $material->is_active ? 'Deactivate' : 'Activate' ?></button><?= form_close() ?><?php endif; ?><a class="btn btn-outline-secondary" href="<?= site_url('materials') ?>">Back to Materials</a></div>
<div class="row g-3 mb-4">
	<div class="col-lg-7"><div class="card shadow-sm h-100"><div class="card-header"><h2 class="card-title mb-0">Material Details</h2></div><div class="card-body"><dl class="row mb-0">
		<dt class="col-sm-4">Code</dt><dd class="col-sm-8"><?= html_escape($material->material_code) ?></dd><dt class="col-sm-4">Name</dt><dd class="col-sm-8"><?= html_escape($material->material_name) ?></dd><dt class="col-sm-4">Status</dt><dd class="col-sm-8"><span class="badge text-bg-<?= $material->is_active ? 'success' : 'secondary' ?>"><?= $material->is_active ? 'Active' : 'Inactive' ?></span></dd><dt class="col-sm-4">Created</dt><dd class="col-sm-8"><?= html_escape(date('d-M-Y h:i A', strtotime($material->created_at))) ?></dd><dt class="col-sm-4">Updated</dt><dd class="col-sm-8"><?= html_escape(date('d-M-Y h:i A', strtotime($material->updated_at))) ?></dd>
	</dl></div></div></div>
	<div class="col-lg-5"><div class="card shadow-sm h-100"><div class="card-header"><h2 class="card-title mb-0">References</h2></div><div class="card-body"><dl class="mb-0"><dt>Category</dt><dd><?= html_escape(trim(($material->material_category_code ?? '').' — '.($material->material_category_name ?? ''), ' —') ?: '—') ?></dd><dt>Group</dt><dd><?= html_escape(trim(($material->material_group_code ?? '').' — '.($material->material_group_name ?? ''), ' —') ?: '—') ?></dd><dt>Default UOM</dt><dd><?= html_escape(trim(($material->uom_code ?? '').' — '.($material->uom_name ?? ''), ' —') ?: '—') ?></dd><dt>Specification</dt><dd class="mb-0"><?= html_escape(trim(($material->specification_source ?? '').' '.($material->specification_code ?? '').' — '.($material->specification_title ?? ''), ' —') ?: '—') ?><?= $material->edition ? ' ('.html_escape($material->edition).')' : '' ?></dd></dl></div></div></div>
</div>
<div class="card shadow-sm mb-4"><div class="card-header"><h2 class="card-title mb-0">Variants and Current Rates</h2></div><div class="card-body"><div class="table-responsive"><table class="table table-striped align-middle w-100 master-data-table"><thead><tr><th>Variant Code</th><th>Size / Description</th><th>UOM</th><th>Current Rate</th><th>Schedule</th><th>Rate Status</th><th>Variant Status</th></tr></thead><tbody><?php foreach ($variants as $variant): ?><tr><td><?= html_escape($variant->material_variant_code) ?></td><td><?= html_escape($variant->size_description ?? '—') ?></td><td><?= html_escape($variant->uom_code ?? '—') ?></td><td data-order="<?= $variant->unit_rate ?? '' ?>"><?= $variant->unit_rate !== NULL ? html_escape(($variant->currency_code ? $variant->currency_code.' ' : '').number_format($variant->unit_rate, 2)) : '—' ?></td><td><?= html_escape($variant->schedule_name ?? '—') ?></td><td><?= html_escape($variant->rate_status ?? '—') ?></td><td><span class="badge text-bg-<?= $variant->is_active ? 'success' : 'secondary' ?>"><?= $variant->is_active ? 'Active' : 'Inactive' ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<div class="card shadow-sm"><div class="card-header"><h2 class="card-title mb-0">Rate History</h2></div><div class="card-body"><div class="table-responsive"><table class="table table-striped align-middle w-100 master-data-table"><thead><tr><th>Variant</th><th>Schedule</th><th>Effective From</th><th>Effective To</th><th>Rate</th><th>Status</th><th>Current</th><th>Recorded</th></tr></thead><tbody><?php foreach ($rates as $rate): ?><tr><td><?= html_escape($rate->material_variant_code) ?></td><td><?= html_escape($rate->schedule_name ?? '—') ?></td><td><?= $rate->effective_from ? html_escape(date('d-M-Y', strtotime($rate->effective_from))) : '—' ?></td><td><?= $rate->effective_to ? html_escape(date('d-M-Y', strtotime($rate->effective_to))) : '—' ?></td><td data-order="<?= html_escape($rate->unit_rate ?? '') ?>"><?= $rate->unit_rate !== NULL ? html_escape(($rate->currency_code ? $rate->currency_code.' ' : '').number_format($rate->unit_rate, 2)) : '—' ?></td><td><?= html_escape($rate->rate_status ?? '—') ?></td><td><?= $rate->is_current ? 'Yes' : 'No' ?></td><td><?= html_escape(date('d-M-Y h:i A', strtotime($rate->created_at))) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
