<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<?php $select=function($name,$label,$rows,$required=FALSE)use($item){$value=set_value($name,$item->{$name}??'');?><div class="col-md-6"><label class="form-label" for="<?=$name?>"><?=html_escape($label)?><?=$required?' *':''?></label><select class="form-select" id="<?=$name?>" name="<?=$name?>" <?=$required?'required':''?>><option value=""><?=$required?'Select…':'None'?></option><?php foreach($rows as $row):?><option value="<?=(int)$row->option_id?>" <?=set_select($name,(string)$row->option_id,(string)$value===(string)$row->option_id)?>><?=html_escape($row->option_label)?></option><?php endforeach;?></select></div><?php }; ?>
<div class="card shadow-sm"><div class="card-header"><h2 class="card-title mb-0">Edit Current Draft Revision</h2></div><div class="card-body"><?php if($form_error):?><div class="alert alert-danger" role="alert"><?=html_escape($form_error)?></div><?php endif;?><?=validation_errors('<div class="alert alert-danger" role="alert">','</div>')?><?=form_open(current_url(),array('novalidate'=>'novalidate'))?><div class="alert alert-info">Enterprise code <strong><?=html_escape($item->enterprise_cost_code?:'Not generated')?></strong>, revision <?=html_escape($item->revision_no)?>, coding status, and approval state are governed and read-only here. Specification is optional.</div><div class="row g-3">
	<div class="col-md-4"><label class="form-label">Item UID</label><input class="form-control" value="<?=html_escape($item->cost_item_uid)?>" readonly></div><div class="col-md-8"><label class="form-label" for="standard_item_name">Standard item name *</label><input class="form-control" id="standard_item_name" name="standard_item_name" maxlength="255" value="<?=set_value('standard_item_name',$item->standard_item_name)?>" required></div><div class="col-12"><label class="form-label" for="standard_description">Standard description *</label><textarea class="form-control" id="standard_description" name="standard_description" rows="4" required><?=set_value('standard_description',$item->standard_description)?></textarea></div>
	<?php $select('division_id','CSI division',$options['divisions'],TRUE);$select('section_id','CSI section',$options['sections'],TRUE);$select('uniformat_level3_id','UniFormat level 3',$options['uniformat3'],TRUE);$select('uniformat_level4_id','UniFormat level 4',$options['uniformat4']);$select('trade_id','Trade',$options['trades'],TRUE);$select('material_group_id','Material group',$options['material_groups']);$select('uom_id','Unit of measure',$options['uoms'],TRUE);$select('specification_id','Specification (optional)',$options['specifications']);$select('attribute_subject_class_id','Attribute subject class',$options['attribute_classes']); ?>
	<?php foreach(array('work_type'=>150,'strength_grade'=>100,'size_dimension'=>150,'application_element'=>200,'finish_condition'=>200)as$name=>$max):?><div class="col-md-6"><label class="form-label" for="<?=$name?>"><?=html_escape(ucwords(str_replace('_',' ',$name)))?></label><input class="form-control" id="<?=$name?>" name="<?=$name?>" maxlength="<?=$max?>" value="<?=set_value($name,$item->{$name}??'')?>"></div><?php endforeach;?>
	<?php foreach(array('measurement_basis','included_work','excluded_work','change_reason')as$name):?><div class="col-md-6"><label class="form-label" for="<?=$name?>"><?=html_escape(ucwords(str_replace('_',' ',$name)))?></label><textarea class="form-control" id="<?=$name?>" name="<?=$name?>" rows="3"><?=set_value($name,$item->{$name}??'')?></textarea></div><?php endforeach;?>
	<div class="col-md-6"><label class="form-label" for="effective_from">Effective from</label><input class="form-control" type="date" id="effective_from" name="effective_from" value="<?=set_value('effective_from',$item->effective_from??'')?>"></div><div class="col-md-6"><label class="form-label" for="effective_to">Effective to</label><input class="form-control" type="date" id="effective_to" name="effective_to" value="<?=set_value('effective_to',$item->effective_to??'')?>"></div>
</div><div class="mt-4"><button class="btn btn-primary" type="submit">Save Draft</button> <a class="btn btn-outline-secondary" href="<?=site_url('standard-cost-items/'.$item->cost_item_id)?>">Cancel</a></div><?=form_close()?></div></div>
