-- Phase 25: reviewed ML-assisted BOQ extraction predictions.
-- The deterministic parser/staging records remain authoritative until an authorized review applies a proposal.

CREATE TABLE IF NOT EXISTS `nexus_ucd`.`ml_extraction_run` (
  `extraction_run_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `boq_import_batch_id` BIGINT UNSIGNED NOT NULL,
  `model_version_id` BIGINT UNSIGNED NULL,
  `extraction_method` VARCHAR(30) NOT NULL,
  `run_status` VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
  `model_code_snapshot` VARCHAR(80) NULL,
  `model_version_snapshot` VARCHAR(50) NULL,
  `feature_schema_version` VARCHAR(50) NOT NULL DEFAULT 'extraction-v1',
  `request_sha256` CHAR(64) NULL,
  `prediction_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `pending_review_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `service_latency_ms` INT UNSIGNED NULL,
  `fallback_reason` VARCHAR(1000) NULL,
  `requested_by` BIGINT UNSIGNED NULL,
  `requested_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` DATETIME NULL,
  `reviewed_at` DATETIME NULL,
  PRIMARY KEY (`extraction_run_id`),
  KEY `idx_ml_extraction_run_batch_date` (`boq_import_batch_id`,`requested_at`),
  KEY `idx_ml_extraction_run_status` (`run_status`,`requested_at`),
  KEY `fk_ml_extraction_run_model` (`model_version_id`),
  KEY `fk_ml_extraction_run_requester` (`requested_by`),
  CONSTRAINT `fk_ml_extraction_run_batch` FOREIGN KEY (`boq_import_batch_id`) REFERENCES `boq_import_batch` (`boq_import_batch_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_ml_extraction_run_model` FOREIGN KEY (`model_version_id`) REFERENCES `ml_model_version` (`model_version_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_ml_extraction_run_requester` FOREIGN KEY (`requested_by`) REFERENCES `app_user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_ml_extraction_run_method` CHECK (`extraction_method` IN ('ML_SERVICE','DETERMINISTIC_FALLBACK')),
  CONSTRAINT `chk_ml_extraction_run_status` CHECK (`run_status` IN ('COMPLETED','REVIEW_PENDING','REVIEWED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nexus_ucd`.`ml_extraction_prediction` (
  `extraction_prediction_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `extraction_run_id` BIGINT UNSIGNED NOT NULL,
  `boq_import_staging_id` BIGINT UNSIGNED NOT NULL,
  `prediction_json` LONGTEXT NOT NULL,
  `confidence_json` LONGTEXT NULL,
  `prediction_status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `applied_json` LONGTEXT NULL,
  `review_reason` VARCHAR(1000) NULL,
  `reviewed_by` BIGINT UNSIGNED NULL,
  `reviewed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`extraction_prediction_id`),
  UNIQUE KEY `uq_ml_extraction_prediction_row` (`extraction_run_id`,`boq_import_staging_id`),
  KEY `idx_ml_extraction_prediction_review` (`extraction_run_id`,`prediction_status`),
  KEY `fk_ml_extraction_prediction_staging` (`boq_import_staging_id`),
  KEY `fk_ml_extraction_prediction_reviewer` (`reviewed_by`),
  CONSTRAINT `fk_ml_extraction_prediction_run` FOREIGN KEY (`extraction_run_id`) REFERENCES `ml_extraction_run` (`extraction_run_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_ml_extraction_prediction_staging` FOREIGN KEY (`boq_import_staging_id`) REFERENCES `boq_import_staging` (`boq_import_staging_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_ml_extraction_prediction_reviewer` FOREIGN KEY (`reviewed_by`) REFERENCES `app_user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_ml_extraction_prediction_status` CHECK (`prediction_status` IN ('PENDING','ACCEPTED','CORRECTED','REJECTED')),
  CONSTRAINT `chk_ml_extraction_prediction_json` CHECK (JSON_VALID(`prediction_json`)),
  CONSTRAINT `chk_ml_extraction_confidence_json` CHECK (`confidence_json` IS NULL OR JSON_VALID(`confidence_json`)),
  CONSTRAINT `chk_ml_extraction_applied_json` CHECK (`applied_json` IS NULL OR JSON_VALID(`applied_json`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nexus_ucd`.`ml_extraction_feedback` (
  `extraction_feedback_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `extraction_prediction_id` BIGINT UNSIGNED NOT NULL,
  `feedback_event` VARCHAR(30) NOT NULL,
  `previous_status` VARCHAR(20) NOT NULL,
  `new_status` VARCHAR(20) NOT NULL,
  `proposal_json` LONGTEXT NOT NULL,
  `applied_json` LONGTEXT NULL,
  `comments` VARCHAR(1000) NULL,
  `feedback_by` BIGINT UNSIGNED NULL,
  `feedback_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`extraction_feedback_id`),
  KEY `idx_ml_extraction_feedback_prediction` (`extraction_prediction_id`,`feedback_at`),
  KEY `fk_ml_extraction_feedback_actor` (`feedback_by`),
  CONSTRAINT `fk_ml_extraction_feedback_prediction` FOREIGN KEY (`extraction_prediction_id`) REFERENCES `ml_extraction_prediction` (`extraction_prediction_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_ml_extraction_feedback_actor` FOREIGN KEY (`feedback_by`) REFERENCES `app_user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_ml_extraction_feedback_event` CHECK (`feedback_event` IN ('PREDICTION_ACCEPTED','PREDICTION_CORRECTED','PREDICTION_REJECTED')),
  CONSTRAINT `chk_ml_extraction_feedback_previous` CHECK (`previous_status` IN ('PENDING','ACCEPTED','CORRECTED','REJECTED')),
  CONSTRAINT `chk_ml_extraction_feedback_new` CHECK (`new_status` IN ('ACCEPTED','CORRECTED','REJECTED')),
  CONSTRAINT `chk_ml_extraction_feedback_proposal` CHECK (JSON_VALID(`proposal_json`)),
  CONSTRAINT `chk_ml_extraction_feedback_applied` CHECK (`applied_json` IS NULL OR JSON_VALID(`applied_json`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
