CREATE TABLE IF NOT EXISTS `boq_header` (
  `boq_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` bigint(20) unsigned NOT NULL,
  `boq_code` varchar(50) NOT NULL,
  `boq_name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `document_reference` varchar(255) DEFAULT NULL,
  `currency_code` char(3) NOT NULL DEFAULT 'PHP',
  `revision_no` varchar(20) DEFAULT NULL,
  `boq_status` varchar(30) NOT NULL DEFAULT 'DRAFT',
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_by` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`boq_id`),
  UNIQUE KEY `uq_boq_header_code` (`boq_code`),
  KEY `idx_boq_header_project_status` (`project_id`,`boq_status`,`is_active`),
  CONSTRAINT `fk_boq_header_project` FOREIGN KEY (`project_id`) REFERENCES `project_master` (`project_id`) ON UPDATE CASCADE,
  CONSTRAINT `chk_boq_header_status` CHECK (`boq_status` IN ('DRAFT','VALIDATED','ACTIVE','ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `boq_item` (
  `boq_item_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `boq_id` bigint(20) unsigned NOT NULL,
  `line_no` int(10) unsigned NOT NULL,
  `item_reference` varchar(100) DEFAULT NULL,
  `section_reference` varchar(255) DEFAULT NULL,
  `item_description` text NOT NULL,
  `uom_id` bigint(20) unsigned DEFAULT NULL,
  `source_uom_text` varchar(50) DEFAULT NULL,
  `quantity` decimal(18,6) NOT NULL,
  `unit_rate` decimal(18,6) DEFAULT NULL,
  `line_amount` decimal(18,2) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_by` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`boq_item_id`),
  UNIQUE KEY `uq_boq_item_line` (`boq_id`,`line_no`),
  KEY `idx_boq_item_reference` (`boq_id`,`item_reference`),
  KEY `fk_boq_item_uom` (`uom_id`),
  CONSTRAINT `fk_boq_item_header` FOREIGN KEY (`boq_id`) REFERENCES `boq_header` (`boq_id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_boq_item_uom` FOREIGN KEY (`uom_id`) REFERENCES `ref_uom` (`uom_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_boq_item_quantity` CHECK (`quantity` >= 0),
  CONSTRAINT `chk_boq_item_rate` CHECK (`unit_rate` IS NULL OR `unit_rate` >= 0),
  CONSTRAINT `chk_boq_item_amount` CHECK (`line_amount` IS NULL OR `line_amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `boq_import_batch` (
  `boq_import_batch_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `boq_id` bigint(20) unsigned NOT NULL,
  `original_file_name` varchar(255) NOT NULL,
  `stored_file_name` varchar(255) NOT NULL,
  `file_type` varchar(10) NOT NULL,
  `file_sha256` char(64) NOT NULL,
  `import_status` varchar(30) NOT NULL DEFAULT 'UPLOADED',
  `total_rows` int(10) unsigned NOT NULL DEFAULT 0,
  `valid_rows` int(10) unsigned NOT NULL DEFAULT 0,
  `invalid_rows` int(10) unsigned NOT NULL DEFAULT 0,
  `imported_rows` int(10) unsigned NOT NULL DEFAULT 0,
  `uploaded_at` datetime NOT NULL DEFAULT current_timestamp(),
  `uploaded_by` bigint(20) unsigned DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`boq_import_batch_id`),
  KEY `idx_boq_import_batch_header_date` (`boq_id`,`uploaded_at`),
  KEY `idx_boq_import_batch_hash` (`file_sha256`),
  KEY `idx_boq_import_batch_status` (`import_status`),
  CONSTRAINT `fk_boq_import_batch_header` FOREIGN KEY (`boq_id`) REFERENCES `boq_header` (`boq_id`) ON UPDATE CASCADE,
  CONSTRAINT `chk_boq_import_batch_type` CHECK (`file_type` IN ('CSV','XLSX')),
  CONSTRAINT `chk_boq_import_batch_status` CHECK (`import_status` IN ('UPLOADED','VALIDATING','INVALID','READY','IMPORTED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `boq_import_staging` (
  `boq_import_staging_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `boq_import_batch_id` bigint(20) unsigned NOT NULL,
  `source_sheet` varchar(100) NOT NULL DEFAULT '',
  `source_row_no` int(10) unsigned NOT NULL,
  `raw_row_data` longtext NOT NULL,
  `item_reference` varchar(100) DEFAULT NULL,
  `section_reference` varchar(255) DEFAULT NULL,
  `item_description` text DEFAULT NULL,
  `source_uom_text` varchar(50) DEFAULT NULL,
  `matched_uom_id` bigint(20) unsigned DEFAULT NULL,
  `quantity_text` varchar(100) DEFAULT NULL,
  `unit_rate_text` varchar(100) DEFAULT NULL,
  `line_amount_text` varchar(100) DEFAULT NULL,
  `quantity` decimal(18,6) DEFAULT NULL,
  `unit_rate` decimal(18,6) DEFAULT NULL,
  `line_amount` decimal(18,2) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `validation_status` varchar(20) NOT NULL DEFAULT 'PENDING',
  `validation_errors` text DEFAULT NULL,
  `boq_item_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `validated_at` datetime DEFAULT NULL,
  `imported_at` datetime DEFAULT NULL,
  PRIMARY KEY (`boq_import_staging_id`),
  UNIQUE KEY `uq_boq_import_staging_row` (`boq_import_batch_id`,`source_sheet`,`source_row_no`),
  KEY `idx_boq_import_staging_status` (`boq_import_batch_id`,`validation_status`),
  KEY `fk_boq_import_staging_uom` (`matched_uom_id`),
  KEY `fk_boq_import_staging_item` (`boq_item_id`),
  CONSTRAINT `fk_boq_import_staging_batch` FOREIGN KEY (`boq_import_batch_id`) REFERENCES `boq_import_batch` (`boq_import_batch_id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_boq_import_staging_uom` FOREIGN KEY (`matched_uom_id`) REFERENCES `ref_uom` (`uom_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_boq_import_staging_item` FOREIGN KEY (`boq_item_id`) REFERENCES `boq_item` (`boq_item_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_boq_import_staging_status` CHECK (`validation_status` IN ('PENDING','VALID','INVALID','IMPORTED','SKIPPED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
