-- Phase 22: additive crew-productivity and derived-labor lineage.
-- Existing business tables and rows are preserved.

CREATE TABLE IF NOT EXISTS `nexus_ucd`.`cost_item_labor_build_up` (
  `cost_item_revision_id` BIGINT UNSIGNED NOT NULL,
  `labor_source_method` VARCHAR(20) NOT NULL DEFAULT 'LEGACY_MANUAL',
  `costing_productivity_id` BIGINT UNSIGNED NULL,
  `crew_id` BIGINT UNSIGNED NULL,
  `duration_days_snapshot` DECIMAL(18,9) NULL,
  `output_quantity_snapshot` DECIMAL(18,6) NULL,
  `output_uom_id` BIGINT UNSIGNED NULL,
  `is_stale` TINYINT(1) NOT NULL DEFAULT 0,
  `applied_by` BIGINT UNSIGNED NULL,
  `applied_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`cost_item_revision_id`),
  KEY `idx_labor_build_up_productivity` (`costing_productivity_id`),
  KEY `idx_labor_build_up_crew` (`crew_id`),
  KEY `idx_labor_build_up_method_stale` (`labor_source_method`, `is_stale`),
  KEY `fk_labor_build_up_output_uom` (`output_uom_id`),
  KEY `fk_labor_build_up_actor` (`applied_by`),
  CONSTRAINT `fk_labor_build_up_revision` FOREIGN KEY (`cost_item_revision_id`) REFERENCES `standard_cost_item_revision` (`cost_item_revision_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_labor_build_up_productivity` FOREIGN KEY (`costing_productivity_id`) REFERENCES `cost_item_productivity` (`productivity_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_labor_build_up_crew` FOREIGN KEY (`crew_id`) REFERENCES `crew_master` (`crew_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_labor_build_up_output_uom` FOREIGN KEY (`output_uom_id`) REFERENCES `ref_uom` (`uom_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_labor_build_up_actor` FOREIGN KEY (`applied_by`) REFERENCES `app_user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_labor_build_up_method` CHECK (`labor_source_method` IN ('LEGACY_MANUAL','MANUAL','CREW_DERIVED')),
  CONSTRAINT `chk_labor_build_up_snapshot` CHECK (`duration_days_snapshot` IS NULL OR `duration_days_snapshot` > 0),
  CONSTRAINT `chk_labor_build_up_output` CHECK (`output_quantity_snapshot` IS NULL OR `output_quantity_snapshot` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nexus_ucd`.`cost_item_labor_derivation` (
  `labor_derivation_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cost_item_revision_id` BIGINT UNSIGNED NOT NULL,
  `cost_item_labor_id` BIGINT UNSIGNED NOT NULL,
  `productivity_id` BIGINT UNSIGNED NULL,
  `crew_member_id` BIGINT UNSIGNED NULL,
  `labor_id` BIGINT UNSIGNED NOT NULL,
  `member_count_snapshot` DECIMAL(10,4) NOT NULL,
  `duration_days_snapshot` DECIMAL(18,9) NOT NULL,
  `output_quantity_snapshot` DECIMAL(18,6) NOT NULL,
  `labor_days_per_item_unit_snapshot` DECIMAL(18,9) NOT NULL,
  `labor_rate_snapshot` DECIMAL(18,6) NOT NULL,
  `currency_code_snapshot` CHAR(3) NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`labor_derivation_id`),
  UNIQUE KEY `uq_labor_derivation_component` (`cost_item_labor_id`),
  UNIQUE KEY `uq_labor_derivation_revision_labor` (`cost_item_revision_id`, `labor_id`),
  KEY `idx_labor_derivation_productivity` (`productivity_id`),
  KEY `idx_labor_derivation_crew_member` (`crew_member_id`),
  KEY `fk_labor_derivation_actor` (`created_by`),
  CONSTRAINT `fk_labor_derivation_revision` FOREIGN KEY (`cost_item_revision_id`) REFERENCES `standard_cost_item_revision` (`cost_item_revision_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_labor_derivation_component` FOREIGN KEY (`cost_item_labor_id`) REFERENCES `cost_item_labor` (`cost_item_labor_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_labor_derivation_productivity` FOREIGN KEY (`productivity_id`) REFERENCES `cost_item_productivity` (`productivity_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_labor_derivation_crew_member` FOREIGN KEY (`crew_member_id`) REFERENCES `crew_member` (`crew_member_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_labor_derivation_labor` FOREIGN KEY (`labor_id`) REFERENCES `labor_master` (`labor_id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_labor_derivation_actor` FOREIGN KEY (`created_by`) REFERENCES `app_user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_labor_derivation_values` CHECK (`member_count_snapshot` > 0 AND `duration_days_snapshot` > 0 AND `output_quantity_snapshot` > 0 AND `labor_days_per_item_unit_snapshot` > 0 AND `labor_rate_snapshot` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
