<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="row justify-content-center"><div class="col-xl-8"><div class="card shadow-sm"><div class="card-header"><h2 class="card-title mb-0"><?=html_escape($page_title)?></h2></div><div class="card-body">
<?php if($form_error):?><div class="alert alert-danger" role="alert"><?=html_escape($form_error)?></div><?php endif;?><?=validation_errors('<div class="alert alert-danger" role="alert">','</div>')?><?=form_open(current_url(),array('novalidate'=>'novalidate'))?>
<?php foreach($entity['fields'] as$name=>$field):?><?php $value=set_value($name,$record->{$name}??'');?><div class="mb-3"><label class="form-label" for="<?=html_escape($name)?>"><?=html_escape($field['label'])?><?=$field['required']?' *':''?></label>
<?php if($field['type']==='textarea'):?><textarea class="form-control" id="<?=html_escape($name)?>" name="<?=html_escape($name)?>" maxlength="<?=(int)$field['max_length']?>" rows="3"><?=html_escape($value)?></textarea>
<?php elseif($field['type']==='lookup'):?><select class="form-select" id="<?=html_escape($name)?>" name="<?=html_escape($name)?>" <?=$field['required']?'required':''?>><option value="">Select…</option><?php foreach($options[$name] as$option):?><option value="<?=html_escape($option->option_id)?>" <?=set_select($name,(string)$option->option_id,(string)$value===(string)$option->option_id)?>><?=html_escape($option->option_label)?></option><?php endforeach;?></select>
<?php elseif($field['type']==='checkbox'):?><div class="form-check"><input class="form-check-input" type="checkbox" id="<?=html_escape($name)?>" name="<?=html_escape($name)?>" value="1" <?=set_checkbox($name,'1',(bool)$value)?>><label class="form-check-label" for="<?=html_escape($name)?>">Yes</label></div>
<?php else:?><input class="form-control" type="<?=$field['type']==='date'?'date':(in_array($field['type'],array('integer','decimal'),TRUE)?'number':'text')?>" <?=$field['type']==='decimal'?'step="any"':''?> id="<?=html_escape($name)?>" name="<?=html_escape($name)?>" value="<?=html_escape($value)?>" <?=isset($field['max_length'])?'maxlength="'.(int)$field['max_length'].'"':''?> <?=$field['required']?'required':''?>><?php endif;?></div><?php endforeach;?>
<?php $active_default=$this->input->method(TRUE)!=='POST'&&($record===NULL||(bool)$record->is_active);?><div class="form-check mb-4"><input class="form-check-input" type="checkbox" id="is_active" name="is_active" value="1" <?=set_checkbox('is_active','1',$active_default)?>><label class="form-check-label" for="is_active">Active</label></div>
<?php if($record!==NULL&&isset($record->created_at)):?><div class="small text-body-secondary mb-3">Created <?=html_escape(date('d-M-Y h:i A',strtotime($record->created_at)))?><?php if(isset($record->updated_at)):?> · Updated <?=html_escape(date('d-M-Y h:i A',strtotime($record->updated_at)))?><?php endif;?></div><?php endif;?>
<button class="btn btn-primary" type="submit">Save Record</button> <a class="btn btn-outline-secondary" href="<?=site_url('references/'.$type)?>">Cancel</a><?=form_close()?></div></div></div></div>
