<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Boq_model extends CI_Model
{
	public function all(){return$this->db->select('b.*,p.project_code,p.project_name,COUNT(DISTINCT i.boq_item_id) AS item_count,COALESCE(SUM(CASE WHEN i.is_active=1 THEN i.line_amount ELSE 0 END),0) AS total_amount')->from('boq_header b')->join('project_master p','p.project_id=b.project_id')->join('boq_item i','i.boq_id=b.boq_id','left')->group_by('b.boq_id')->order_by('b.is_active','DESC')->order_by('b.boq_code')->get()->result();}
	public function find($id){$r=$this->db->select('b.*,p.project_code,p.project_name')->from('boq_header b')->join('project_master p','p.project_id=b.project_id')->where('b.boq_id',(int)$id)->get()->row();return$r?:NULL;}
	public function projects(){return$this->db->select("project_id AS option_id,CONCAT(project_code,' — ',project_name) AS option_label",FALSE)->where('is_active',1)->order_by('project_code')->get('project_master')->result();}
	public function project_exists($id){return$this->db->where('project_id',(int)$id)->count_all_results('project_master')>0;}
	public function code_exists($code,$exclude=NULL){$this->db->where('boq_code',$code);if($exclude)$this->db->where('boq_id !=',(int)$exclude);return$this->db->count_all_results('boq_header')>0;}
	public function create(array$data){return$this->db->insert('boq_header',$data)?(int)$this->db->insert_id():0;}
	public function update($id,array$data){return$this->db->where('boq_id',(int)$id)->update('boq_header',$data);}
	public function status($id,$active,$actor){return$this->db->where('boq_id',(int)$id)->update('boq_header',array('is_active'=>$active?1:0,'updated_by'=>(int)$actor));}
	public function delete_boq($id)
	{
		$id=(int)$id;$files=array_column($this->db->select('stored_file_name')->where('boq_id',$id)->get('boq_import_batch')->result_array(),'stored_file_name');
		$batch_ids=array_map('intval',array_column($this->db->select('boq_import_batch_id')->where('boq_id',$id)->get('boq_import_batch')->result_array(),'boq_import_batch_id'));
		$item_ids=array_map('intval',array_column($this->db->select('boq_item_id')->where('boq_id',$id)->get('boq_item')->result_array(),'boq_item_id'));
		$this->db->trans_begin();
		if($batch_ids)$this->db->where_in('boq_import_batch_id',$batch_ids)->delete('boq_import_staging');
		$this->db->where('boq_id',$id)->delete('boq_import_batch');
		if($item_ids){$this->db->where_in('boq_item_id',$item_ids)->delete('boq_item_mapping_history');$this->db->where_in('boq_item_id',$item_ids)->delete('boq_item_mapping');$this->db->where_in('boq_item_id',$item_ids)->delete('boq_mapping_candidate');$this->db->where_in('boq_item_id',$item_ids)->delete('boq_item');}
		$this->db->where('boq_id',$id)->delete('boq_header');
		if($this->db->trans_status()===FALSE){$this->db->trans_rollback();return FALSE;}
		$this->db->trans_commit();return$files;
	}
	public function items($boq_id){return$this->db->select('i.*,u.uom_code,u.uom_name,m.mapping_status,c.cost_item_revision_id,r.enterprise_cost_code,r.standard_item_name,si.cost_item_id,si.cost_item_uid')->from('boq_item i')->join('ref_uom u','u.uom_id=i.uom_id','left')->join('boq_item_mapping m','m.boq_item_id=i.boq_item_id','left')->join('boq_mapping_candidate c','c.boq_mapping_candidate_id=m.boq_mapping_candidate_id','left')->join('standard_cost_item_revision r','r.cost_item_revision_id=c.cost_item_revision_id','left')->join('standard_cost_item si','si.cost_item_id=r.cost_item_id','left')->where('i.boq_id',(int)$boq_id)->order_by('i.line_no')->get()->result();}
	public function item($boq_id,$item_id){$r=$this->db->where('boq_id',(int)$boq_id)->where('boq_item_id',(int)$item_id)->get('boq_item')->row();return$r?:NULL;}
	public function uoms(){return$this->db->select("uom_id AS option_id,CONCAT(uom_code,' — ',uom_name) AS option_label",FALSE)->where('is_active',1)->order_by('uom_code')->get('ref_uom')->result();}
	public function uom_exists($id){return$this->db->where('uom_id',(int)$id)->count_all_results('ref_uom')>0;}
	public function line_exists($boq,$line,$exclude=NULL){$this->db->where('boq_id',(int)$boq)->where('line_no',(int)$line);if($exclude)$this->db->where('boq_item_id !=',(int)$exclude);return$this->db->count_all_results('boq_item')>0;}
	public function create_item(array$data){return$this->db->insert('boq_item',$data)?(int)$this->db->insert_id():0;}
	public function update_item($id,array$data){return$this->db->where('boq_item_id',(int)$id)->update('boq_item',$data);}
	public function item_status($id,$active,$actor){return$this->db->where('boq_item_id',(int)$id)->update('boq_item',array('is_active'=>$active?1:0,'updated_by'=>(int)$actor));}
	public function batches($boq){return$this->db->select('b.*,COALESCE(u.display_name,u.username) AS uploaded_by_name',FALSE)->from('boq_import_batch b')->join('app_user u','u.user_id=b.uploaded_by','left')->where('b.boq_id',(int)$boq)->order_by('b.uploaded_at','DESC')->get()->result();}
	public function batch($boq,$batch){$r=$this->db->where('boq_id',(int)$boq)->where('boq_import_batch_id',(int)$batch)->get('boq_import_batch')->row();return$r?:NULL;}
	public function staged($batch){return$this->db->where('boq_import_batch_id',(int)$batch)->order_by('source_row_no')->get('boq_import_staging')->result();}

	public function stage_import($boq,$file,$type,$sheet,array$rows,$actor,array$profile=array())
	{
		$headers=array_shift($rows);if(!$headers)throw new RuntimeException('The import file is empty.');$map=$this->header_map($headers);foreach(array('item_description','quantity')as$required)if(!isset($map[$required]))throw new RuntimeException('Missing required column: '.$required.'.');
		$this->db->trans_start();$this->db->insert('boq_import_batch',array('boq_id'=>(int)$boq,'original_file_name'=>$file['original'],'stored_file_name'=>$file['stored'],'file_type'=>$type,'file_sha256'=>$file['sha256'],'source_sheet'=>$sheet,'source_declared_total'=>$profile['source_declared_total']??NULL,'parsed_line_total'=>$profile['parsed_line_total']??NULL,'total_variance'=>$profile['total_variance']??NULL,'unpriced_rows'=>(int)($profile['unpriced_rows']??0),'normalization_notes'=>$profile['normalization_notes']??NULL,'import_status'=>'VALIDATING','uploaded_by'=>(int)$actor));$batch=(int)$this->db->insert_id();$valid=0;$invalid=0;$row_no=1;
		foreach($rows as$row){$row_no++;if(!array_filter($row,static function($v){return trim((string)$v)!=='';}))continue;$data=$this->validate_row($row,$map);$errors=$data['errors'];unset($data['errors']);$data+=array('boq_import_batch_id'=>$batch,'source_sheet'=>substr($sheet,0,100),'source_row_no'=>$row_no,'raw_row_data'=>json_encode($row,JSON_UNESCAPED_UNICODE),'validation_status'=>$errors?'INVALID':'VALID','validation_errors'=>$errors?json_encode($errors,JSON_UNESCAPED_UNICODE):NULL,'validated_at'=>date('Y-m-d H:i:s'));$this->db->insert('boq_import_staging',$data);$errors?$invalid++:$valid++;}
		$total=$valid+$invalid;$status=$total===0?'INVALID':($invalid?'INVALID':'READY');$this->db->where('boq_import_batch_id',$batch)->update('boq_import_batch',array('import_status'=>$status,'total_rows'=>$total,'valid_rows'=>$valid,'invalid_rows'=>$invalid,'completed_at'=>date('Y-m-d H:i:s')));$this->db->trans_complete();if(!$this->db->trans_status())throw new RuntimeException('Unable to stage the import batch.');return$batch;
	}

	public function commit_batch($boq,$batch,$actor)
	{
		$b=$this->batch($boq,$batch);if(!$b||$b->import_status!=='READY')return FALSE;$rows=$this->db->where('boq_import_batch_id',(int)$batch)->where('validation_status','VALID')->order_by('source_row_no')->get('boq_import_staging')->result();$next=(int)($this->db->select_max('line_no','max_line')->where('boq_id',(int)$boq)->get('boq_item')->row()->max_line??0)+1;$this->db->trans_start();$count=0;
		foreach($rows as$r){$this->db->insert('boq_item',array('boq_id'=>(int)$boq,'line_no'=>$next++,'item_reference'=>$r->item_reference,'section_reference'=>$r->section_reference,'item_description'=>$r->item_description,'uom_id'=>$r->matched_uom_id,'source_uom_text'=>$r->source_uom_text,'quantity'=>$r->quantity,'unit_rate'=>$r->unit_rate,'line_amount'=>$r->line_amount,'notes'=>$r->notes,'is_active'=>1,'created_by'=>(int)$actor,'updated_by'=>(int)$actor));$item=(int)$this->db->insert_id();$this->db->where('boq_import_staging_id',$r->boq_import_staging_id)->update('boq_import_staging',array('validation_status'=>'IMPORTED','boq_item_id'=>$item,'imported_at'=>date('Y-m-d H:i:s')));$count++;}
		$this->db->where('boq_import_batch_id',(int)$batch)->where('import_status','READY')->update('boq_import_batch',array('import_status'=>'IMPORTED','imported_rows'=>$count,'completed_at'=>date('Y-m-d H:i:s')));$this->db->where('boq_id',(int)$boq)->where('boq_status','DRAFT')->update('boq_header',array('boq_status'=>'VALIDATED','updated_by'=>(int)$actor));$this->db->trans_complete();return$this->db->trans_status();
	}

	private function header_map(array$headers){$aliases=array('item_no'=>'item_reference','item_code'=>'item_reference','description'=>'item_description','item'=>'item_description','unit'=>'source_uom_text','uom'=>'source_uom_text','rate'=>'unit_rate','amount'=>'line_amount','section'=>'section_reference');$map=array();foreach($headers as$i=>$h){$key=preg_replace('/[^a-z0-9]+/','_',strtolower(trim((string)$h)));$key=trim($key,'_');$key=$aliases[$key]??$key;if(in_array($key,array('item_reference','section_reference','item_description','source_uom_text','quantity','unit_rate','line_amount','notes','source_row_no'),TRUE))$map[$key]=$i;}return$map;}
	private function validate_row(array$row,array$map){$get=static function($key)use($row,$map){return isset($map[$key])?trim((string)($row[$map[$key]]??'')):'';};$description=$get('item_description');$uom=$get('source_uom_text');$q=$this->number($get('quantity'));$rate=$this->number($get('unit_rate'));$amount=$this->number($get('line_amount'));$errors=array();if($description==='')$errors[]='Item description is required.';if($q===NULL||$q<0)$errors[]='Quantity must be a non-negative number.';if($get('unit_rate')!==''&&($rate===NULL||$rate<0))$errors[]='Unit rate must be a non-negative number.';if($get('line_amount')!==''&&($amount===NULL||$amount<0))$errors[]='Line amount must be a non-negative number.';$uom_id=NULL;if($uom!==''){$match=$this->match_uom($uom);if($match)$uom_id=$match->uom_id;else$errors[]='UOM code or supported source alias was not found.';}$arithmetic_tolerance=$q===NULL?0.02:0.02+(abs($q)*0.0000005);if($q!==NULL&&$rate!==NULL&&$amount!==NULL&&abs(($q*$rate)-$amount)>$arithmetic_tolerance)$errors[]='Line amount does not equal quantity × unit rate.';$result=array('item_reference'=>$this->null($get('item_reference')),'section_reference'=>$this->null($get('section_reference')),'item_description'=>$this->null($description),'source_uom_text'=>$this->null($uom),'matched_uom_id'=>$uom_id,'quantity_text'=>$this->null($get('quantity')),'unit_rate_text'=>$this->null($get('unit_rate')),'line_amount_text'=>$this->null($get('line_amount')),'quantity'=>$q,'unit_rate'=>$rate,'line_amount'=>$amount,'notes'=>$this->null($get('notes')),'errors'=>$errors);$source_row=$this->number($get('source_row_no'));if($source_row!==NULL)$result['source_row_no']=(int)$source_row;return$result;}
	private function match_uom($source){$key=strtolower(trim($source));$key=str_replace(array('²','³'),array('2','3'),$key);$token=preg_replace('/[^a-z0-9]+/','',$key);$aliases=array('nos'=>'No','no'=>'No','number'=>'No','lm'=>'lin_m','lnm'=>'lin_m','linearmeter'=>'lin_m','linearmeters'=>'lin_m','m2'=>'m2','sqm'=>'m2','squaremeter'=>'m2','squaremeters'=>'m2','m3'=>'m3','cum'=>'m3','cubicmeter'=>'m3','cubicmeters'=>'m3','sets'=>'set','set'=>'set','pcs'=>'pc','pieces'=>'pc','piece'=>'pc','kgs'=>'kg','kilograms'=>'kg','months'=>'month','unit'=>'each','units'=>'each','assy'=>'item','assembly'=>'item','bags'=>'bag');$code=$aliases[$token]??$source;return$this->db->where('UPPER(uom_code)',strtoupper($code))->where('is_active',1)->get('ref_uom')->row();}
	private function number($value){if($value==='')return NULL;$clean=str_replace(array(',',' '),'',$value);return is_numeric($clean)?(float)$clean:NULL;}
	private function null($value){return$value===''?NULL:$value;}
}
