<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Cost_intelligence_model extends CI_Model
{
	private $bands_cache=NULL;
	public function dashboard()
	{
		$ranges=$this->ranges();$outliers=array();foreach($ranges as$range)foreach($range->outliers as$outlier)$outliers[]=$outlier;usort($outliers,static function($a,$b){return$b->deviation_percent<=>$a->deviation_percent;});
		return array('ranges'=>$ranges,'outliers'=>$outliers,'trends'=>$this->trends(),'coverage'=>$this->coverage(),'bands'=>$this->confidence_bands());
	}

	public function suggestions($text,$uom_id=NULL,$limit=20)
	{
		$query_tokens=$this->tokens($text);if(!$query_tokens)return array();$rows=$this->db->select("r.cost_item_revision_id,r.cost_item_id,r.enterprise_cost_code,r.standard_item_name,r.standard_description,r.revision_no,r.revision_status,r.uom_id,u.uom_code,i.cost_item_uid,COALESCE((SELECT GROUP_CONCAT(k.keyword SEPARATOR ' ') FROM cost_item_keyword k WHERE k.cost_item_id=i.cost_item_id),'') AS keywords,COALESCE((SELECT GROUP_CONCAT(s.synonym_text SEPARATOR ' ') FROM cost_item_synonym s WHERE s.cost_item_id=i.cost_item_id AND s.is_approved=1),'') AS synonyms",FALSE)->from('standard_cost_item_revision r')->join('standard_cost_item i','i.cost_item_id=r.cost_item_id')->join('ref_uom u','u.uom_id=r.uom_id','left')->where('r.is_current',1)->where('i.lifecycle_status','ACTIVE')->get()->result();$results=array();$normalized_query=$this->normalize($text);
		foreach($rows as$row){$candidate_text=trim($row->standard_item_name.' '.$row->standard_description.' '.$row->keywords.' '.$row->synonyms);$candidate_tokens=$this->tokens($candidate_text);$intersection=array_values(array_intersect($query_tokens,$candidate_tokens));$union=array_values(array_unique(array_merge($query_tokens,$candidate_tokens)));$coverage_score=$query_tokens?65*(count($intersection)/count($query_tokens)):0;$specificity_score=$union?10*(count($intersection)/count($union)):0;$token_score=$coverage_score+$specificity_score;$phrase_score=$normalized_query!==''&&strpos($this->normalize($candidate_text),$normalized_query)!==FALSE?10:0;$uom_score=$uom_id!==NULL&&(int)$row->uom_id===(int)$uom_id?15:0;$score=round(min(100,$token_score+$phrase_score+$uom_score),2);if($score<=0)continue;$row->similarity_score=$score;$row->confidence=$this->band_for($score);$parts=array();$parts[]=$intersection?'Matched terms: '.implode(', ',array_slice($intersection,0,8)).'.':'No exact meaningful terms matched.';$parts[]='Query-term coverage and specificity contribute '.number_format($token_score,2).' of 75 points.';if($phrase_score)$parts[]='The normalized query appears as a phrase (+10).';if($uom_id!==NULL)$parts[]=$uom_score?'UOM matches (+15).':'UOM does not match (+0).';$parts[]='No mapping or master data was changed.';$row->explanation=implode(' ',$parts);$results[]=$row;}
		usort($results,static function($a,$b){return$b->similarity_score<=>$a->similarity_score?:strcmp($a->standard_item_name,$b->standard_item_name);});return array_slice($results,0,(int)$limit);
	}

	public function uoms(){return$this->db->select("uom_id AS option_id,CONCAT(uom_code,' — ',uom_name) AS option_label",FALSE)->where('is_active',1)->order_by('uom_code')->get('ref_uom')->result();}

	private function ranges()
	{
		$rows=$this->db->select('rh.rate_history_id,rh.unit_rate,rh.currency_code,rh.rate_date,rh.project_id,rh.location_id,rh.contractor_supplier,rh.is_validated,rh.validation_status,rh.rate_source_type_id,rh.rate_basis_id,r.cost_item_id,r.enterprise_cost_code,r.standard_item_name,r.division_id,r.trade_id,r.uom_id,d.division_code,d.division_name,t.trade_code,t.trade_name,u.uom_code,i.cost_item_uid')->from('cost_item_rate_history rh')->join('standard_cost_item_revision r','r.cost_item_revision_id=rh.cost_item_revision_id')->join('standard_cost_item i','i.cost_item_id=r.cost_item_id')->join('ref_csi_division d','d.division_id=r.division_id','left')->join('ref_trade t','t.trade_id=r.trade_id','left')->join('ref_uom u','u.uom_id=r.uom_id','left')->where('rh.unit_rate IS NOT NULL',NULL,FALSE)->get()->result();$groups=array();
		foreach($rows as$row){$key=(int)$row->division_id.'|'.(int)$row->trade_id.'|'.(int)$row->uom_id.'|'.(string)$row->currency_code;if(!isset($groups[$key]))$groups[$key]=array('label'=>trim(($row->division_code?:'Unclassified').' / '.($row->trade_code?:'Unclassified'),' /'),'uom'=>$row->uom_code?:'Not recorded','currency'=>$row->currency_code?:'Not recorded','rows'=>array(),'values'=>array(),'validated'=>0,'dated'=>0,'project'=>0,'location'=>0,'source'=>0,'basis'=>0);$group=&$groups[$key];$group['rows'][]=$row;$group['values'][]=(float)$row->unit_rate;if($row->is_validated||$row->validation_status==='VALID')$group['validated']++;if($row->rate_date)$group['dated']++;if($row->project_id)$group['project']++;if($row->location_id)$group['location']++;if($row->rate_source_type_id)$group['source']++;if($row->rate_basis_id)$group['basis']++;unset($group);}
		$result=array();foreach($groups as$group){sort($group['values'],SORT_NUMERIC);$n=count($group['values']);if($n<5)continue;$p25=$this->percentile($group['values'],.25);$median=$this->percentile($group['values'],.5);$p75=$this->percentile($group['values'],.75);$iqr=$p75-$p25;$lower=max(0,$p25-(1.5*$iqr));$upper=$p75+(1.5*$iqr);$sample_score=min(35,($n/20)*35);$source_score=15*($group['source']/$n);$basis_score=15*($group['basis']/$n);$validation_score=20*($group['validated']/$n);$recency_score=10*($group['dated']/$n);$location_score=5*($group['location']/$n);$score=round($sample_score+$source_score+$basis_score+$validation_score+$recency_score+$location_score,2);$band=$this->band_for($score);$outliers=array();foreach($group['rows']as$row)if($row->unit_rate<$lower||$row->unit_rate>$upper){$center=$median?:1;$row->deviation_percent=round(abs($row->unit_rate-$median)/$center*100,2);$row->direction=$row->unit_rate<$lower?'LOW':'HIGH';$row->group_label=$group['label'];$row->lower_bound=$lower;$row->upper_bound=$upper;$outliers[]=$row;}$result[]=(object)array('label'=>$group['label'],'uom'=>$group['uom'],'currency'=>$group['currency'],'sample_count'=>$n,'minimum'=>$group['values'][0],'p25'=>$p25,'median'=>$median,'p75'=>$p75,'maximum'=>$group['values'][$n-1],'lower_fence'=>$lower,'upper_fence'=>$upper,'outlier_count'=>count($outliers),'confidence_score'=>$score,'confidence'=>$band,'confidence_basis'=>'Sample '.number_format($sample_score,1).'/35; source type '.number_format($source_score,1).'/15; rate basis '.number_format($basis_score,1).'/15; validation '.number_format($validation_score,1).'/20; dated evidence '.number_format($recency_score,1).'/10; governed location '.number_format($location_score,1).'/5.','outliers'=>$outliers);}
		usort($result,static function($a,$b){return$b->sample_count<=>$a->sample_count;});return$result;
	}

	private function trends()
	{
		return$this->db->select("YEAR(rh.rate_date) AS period_year,r.uom_id,u.uom_code,r.division_id,d.division_code,COUNT(*) AS sample_count,AVG(rh.unit_rate) AS average_rate,MIN(rh.unit_rate) AS minimum_rate,MAX(rh.unit_rate) AS maximum_rate",FALSE)->from('cost_item_rate_history rh')->join('standard_cost_item_revision r','r.cost_item_revision_id=rh.cost_item_revision_id')->join('ref_uom u','u.uom_id=r.uom_id','left')->join('ref_csi_division d','d.division_id=r.division_id','left')->where('rh.rate_date IS NOT NULL',NULL,FALSE)->group_by(array('YEAR(rh.rate_date)','r.uom_id','r.division_id'))->order_by('period_year')->get()->result();
	}

	private function coverage()
	{
		return$this->db->select("COUNT(*) AS observation_count,COUNT(DISTINCT cost_item_revision_id) AS revision_count,SUM(project_id IS NOT NULL) AS project_count,SUM(location_id IS NOT NULL) AS location_count,SUM(rate_date IS NOT NULL) AS dated_count,SUM(contractor_supplier IS NOT NULL AND contractor_supplier!='') AS contractor_count,SUM(currency_code IS NOT NULL AND currency_code!='') AS currency_count,SUM(is_validated=1 OR validation_status='VALID') AS validated_count",FALSE)->get('cost_item_rate_history')->row();
	}

	private function confidence_bands(){if($this->bands_cache===NULL)$this->bands_cache=$this->db->where('is_active',1)->order_by('sort_order')->get('ref_confidence_band')->result();return$this->bands_cache;}
	private function band_for($score){foreach($this->confidence_bands()as$band)if($score>=(float)$band->minimum_score&&$score<=(float)$band->maximum_score)return$band;return(object)array('confidence_code'=>'UNRATED','confidence_name'=>'Unrated','is_recommendable'=>0,'description'=>'No confidence band covers this score.');}
	private function percentile(array$values,$p){$n=count($values);if(!$n)return NULL;if($n===1)return$values[0];$position=($n-1)*$p;$lower=(int)floor($position);$upper=(int)ceil($position);return$lower===$upper?$values[$lower]:$values[$lower]+(($values[$upper]-$values[$lower])*($position-$lower));}
	private function normalize($text){$text=html_entity_decode((string)$text,ENT_QUOTES,'UTF-8');$text=strtolower($text);$text=str_replace(array('ø','Ø','²','³'),array(' diameter ',' diameter ','2','3'),$text);$text=preg_replace('/[^a-z0-9]+/',' ',$text);return trim(preg_replace('/\s+/',' ',$text));}
	private function tokens($text){$stop=array_flip(array('and','the','for','with','from','into','per','type','work','works','supply','install','installation','including','complete','of','in','on','to','a','an'));$tokens=array();foreach(explode(' ',$this->normalize($text))as$token)if(strlen($token)>=2&&!isset($stop[$token]))$tokens[$token]=$token;return array_values($tokens);}
}
