<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Ml_governance_model extends CI_Model
{
	public function datasets(){return$this->db->select('d.*,COUNT(DISTINCT v.dataset_version_id) version_count,MAX(v.version_no) latest_version')->from('ml_dataset d')->join('ml_dataset_version v','v.dataset_id=d.dataset_id','left')->group_by('d.dataset_id')->order_by('d.dataset_code')->get()->result();}
	public function jobs(){return$this->db->select('j.*,d.dataset_code,v.version_no,COALESCE(u.display_name,u.username) requested_by_name',FALSE)->from('ml_job j')->join('ml_dataset_version v','v.dataset_version_id=j.dataset_version_id','left')->join('ml_dataset d','d.dataset_id=v.dataset_id','left')->join('app_user u','u.user_id=j.requested_by','left')->order_by('j.requested_at','DESC')->limit(100)->get()->result();}
	public function models(){return$this->db->select('m.*,d.dataset_code,v.version_no')->from('ml_model_version m')->join('ml_dataset_version v','v.dataset_version_id=m.trained_dataset_version_id','left')->join('ml_dataset d','d.dataset_id=v.dataset_id','left')->order_by('m.created_at','DESC')->get()->result();}
	public function find_dataset($id){$row=$this->db->where('dataset_id',(int)$id)->get('ml_dataset')->row();return$row?:NULL;}
	public function versions($id){return$this->db->where('dataset_id',(int)$id)->order_by('version_no','DESC')->get('ml_dataset_version')->result();}
	public function find_version($id){$row=$this->db->select('v.*,d.dataset_code,d.dataset_name,d.capability')->from('ml_dataset_version v')->join('ml_dataset d','d.dataset_id=v.dataset_id')->where('v.dataset_version_id',(int)$id)->get()->row();return$row?:NULL;}
	public function records($id,$limit=500){return$this->db->select('r.*,COALESCE(u.display_name,u.username) reviewed_by_name',FALSE)->from('ml_dataset_record r')->join('app_user u','u.user_id=r.reviewed_by','left')->where('r.dataset_version_id',(int)$id)->order_by('r.dataset_record_id')->limit((int)$limit)->get()->result();}
	public function feedback($id){return$this->db->select('f.*,COALESCE(u.display_name,u.username) feedback_by_name',FALSE)->from('ml_feedback f')->join('ml_dataset_record r','r.dataset_record_id=f.dataset_record_id')->join('app_user u','u.user_id=f.feedback_by','left')->where('r.dataset_version_id',(int)$id)->order_by('f.feedback_at','DESC')->limit(200)->get()->result();}
	public function record_counts($id){$row=$this->db->select("COUNT(*) total,SUM(label_status='PENDING') pending,SUM(label_status='APPROVED') approved,SUM(label_status='REJECTED') rejected",FALSE)->where('dataset_version_id',(int)$id)->get('ml_dataset_record')->row();return$row?:(object)array('total'=>0,'pending'=>0,'approved'=>0,'rejected'=>0);}
	public function create_dataset(array$data){return$this->db->insert('ml_dataset',$data)?(int)$this->db->insert_id():0;}
	public function code_exists($code){return$this->db->where('dataset_code',$code)->count_all_results('ml_dataset')>0;}

	public function create_version($dataset_id,$notes,$actor)
	{
		$dataset=$this->find_dataset($dataset_id);if(!$dataset||$dataset->dataset_status!=='ACTIVE')return array('error'=>'The dataset is invalid or inactive.');$cutoff=date('Y-m-d H:i:s');$this->db->trans_begin();$lock=$this->db->query("SELECT GET_LOCK('nexus_ucd_ml_dataset_version_".(int)$dataset_id."',10) acquired")->row();if(!$lock||(int)$lock->acquired!==1){$this->db->trans_rollback();return array('error'=>'Unable to reserve a dataset version number.');}$max=$this->db->select_max('version_no','n')->where('dataset_id',(int)$dataset_id)->get('ml_dataset_version')->row();$version=(int)($max->n??0)+1;$this->db->insert('ml_dataset_version',array('dataset_id'=>(int)$dataset_id,'version_no'=>$version,'source_cutoff_at'=>$cutoff,'notes'=>$notes,'created_by'=>(int)$actor));$id=(int)$this->db->insert_id();$rows=$this->source_rows($dataset->capability,$cutoff);foreach($rows as$row){$row['dataset_version_id']=$id;$this->db->insert('ml_dataset_record',$row);}$this->db->where('dataset_version_id',$id)->update('ml_dataset_version',array('record_count'=>count($rows)));$ok=$this->db->trans_status();if($ok)$this->db->trans_commit();else$this->db->trans_rollback();$this->db->query("SELECT RELEASE_LOCK('nexus_ucd_ml_dataset_version_".(int)$dataset_id."')");return$ok?array('dataset_version_id'=>$id,'record_count'=>count($rows)):array('error'=>'Unable to create the dataset snapshot.');
	}

	public function review_record($record_id,$status,$comments,$actor)
	{
		$record=$this->db->select('r.*,v.version_status')->from('ml_dataset_record r')->join('ml_dataset_version v','v.dataset_version_id=r.dataset_version_id')->where('r.dataset_record_id',(int)$record_id)->get()->row();if(!$record||$record->version_status!=='DRAFT')return FALSE;$events=array('APPROVED'=>'LABEL_APPROVED','REJECTED'=>'LABEL_REJECTED','PENDING'=>'LABEL_REOPENED');if(!isset($events[$status]))return FALSE;$this->db->trans_start();$this->db->where('dataset_record_id',(int)$record_id)->update('ml_dataset_record',array('label_status'=>$status,'review_notes'=>$comments,'reviewed_by'=>(int)$actor,'reviewed_at'=>date('Y-m-d H:i:s')));$this->db->insert('ml_feedback',array('dataset_record_id'=>(int)$record_id,'feedback_event'=>$events[$status],'previous_label_status'=>$record->label_status,'new_label_status'=>$status,'comments'=>$comments,'feedback_by'=>(int)$actor));$this->db->trans_complete();return$this->db->trans_status();
	}

	public function freeze($version_id,$actor)
	{
		$v=$this->find_version($version_id);if(!$v||$v->version_status!=='DRAFT')return array('error'=>'Only a Draft dataset version can be frozen.');$counts=$this->record_counts($version_id);if((int)$counts->pending>0)return array('error'=>'Review every pending label before freezing.');if((int)$counts->approved<1)return array('error'=>'At least one approved label is required before freezing.');$hashes=$this->db->select('record_sha256')->where('dataset_version_id',(int)$version_id)->where('label_status','APPROVED')->order_by('dataset_record_id')->get('ml_dataset_record')->result_array();$manifest=hash('sha256',implode("\n",array_column($hashes,'record_sha256')));$key='dataset-export-'.$version_id.'-'.$manifest;$payload=$this->json(array('dataset_version_id'=>(int)$version_id,'manifest_sha256'=>$manifest));$this->db->trans_start();$this->db->where('dataset_version_id',(int)$version_id)->where('version_status','DRAFT')->update('ml_dataset_version',array('version_status'=>'FROZEN','record_count'=>(int)$counts->total,'approved_label_count'=>(int)$counts->approved,'manifest_sha256'=>$manifest,'frozen_by'=>(int)$actor,'frozen_at'=>date('Y-m-d H:i:s')));if($this->db->affected_rows()!==1){$this->db->trans_rollback();return array('error'=>'The dataset version changed before it could be frozen.');}$this->db->insert('ml_job',array('job_type'=>'DATASET_EXPORT','capability'=>$v->capability,'dataset_version_id'=>(int)$version_id,'job_status'=>'QUEUED','idempotency_key'=>$key,'payload_json'=>$payload,'requested_by'=>(int)$actor));$this->db->trans_complete();return$this->db->trans_status()?array('ok'=>TRUE):array('error'=>'Unable to freeze and queue the export.');
	}

	public function approve($version_id,$actor)
	{
		$v=$this->find_version($version_id);if(!$v||$v->version_status!=='FROZEN'||!$v->artifact_file_name||!$v->artifact_sha256)return FALSE;if(!$this->db->where('dataset_version_id',(int)$version_id)->where('job_type','DATASET_EXPORT')->where('job_status','SUCCEEDED')->count_all_results('ml_job'))return FALSE;return$this->db->where('dataset_version_id',(int)$version_id)->where('version_status','FROZEN')->update('ml_dataset_version',array('version_status'=>'APPROVED','approved_by'=>(int)$actor,'approved_at'=>date('Y-m-d H:i:s')));
	}

	public function process_next_export($artifact_root)
	{
		$this->db->trans_begin();$job=$this->db->query("SELECT * FROM ml_job WHERE job_type='DATASET_EXPORT' AND job_status='QUEUED' ORDER BY requested_at,ml_job_id LIMIT 1 FOR UPDATE")->row();if(!$job){$this->db->trans_commit();return array('message'=>'No queued dataset export job.');}$worker=gethostname().':'.getmypid();$this->db->where('ml_job_id',$job->ml_job_id)->update('ml_job',array('job_status'=>'RUNNING','attempt_count'=>(int)$job->attempt_count+1,'started_at'=>date('Y-m-d H:i:s'),'worker_reference'=>$worker));$this->db->trans_commit();
		$path=NULL;try{$v=$this->find_version($job->dataset_version_id);if(!$v||$v->version_status!=='FROZEN')throw new Exception('Dataset version is not frozen.');if(!is_dir($artifact_root)&&!mkdir($artifact_root,0750,TRUE))throw new Exception('Artifact directory could not be created.');if(!is_writable($artifact_root))throw new Exception('Artifact directory is not writable.');$file='dataset_'.$v->dataset_id.'_v'.$v->version_no.'_'.substr($v->manifest_sha256,0,12).'.jsonl';$path=$artifact_root.DIRECTORY_SEPARATOR.$file;$handle=fopen($path,'wb');if(!$handle)throw new Exception('Artifact file could not be opened.');$header=$this->json(array('_manifest'=>array('dataset_code'=>$v->dataset_code,'version_no'=>(int)$v->version_no,'capability'=>$v->capability,'source_cutoff_at'=>$v->source_cutoff_at,'manifest_sha256'=>$v->manifest_sha256,'approved_label_count'=>(int)$v->approved_label_count)));fwrite($handle,$header."\n");$records=$this->db->where('dataset_version_id',(int)$v->dataset_version_id)->where('label_status','APPROVED')->order_by('dataset_record_id')->get('ml_dataset_record')->result();foreach($records as$r)fwrite($handle,$this->json(array('source_identity'=>$r->source_identity,'record_type'=>$r->record_type,'split_group_key'=>$r->split_group_key,'payload'=>json_decode($r->payload_json,TRUE),'label'=>json_decode($r->label_json,TRUE),'record_sha256'=>$r->record_sha256))."\n");fclose($handle);$sha=hash_file('sha256',$path);$this->db->trans_start();$this->db->where('dataset_version_id',$v->dataset_version_id)->where('version_status','FROZEN')->update('ml_dataset_version',array('artifact_file_name'=>$file,'artifact_sha256'=>$sha));$this->db->where('ml_job_id',$job->ml_job_id)->update('ml_job',array('job_status'=>'SUCCEEDED','completed_at'=>date('Y-m-d H:i:s'),'result_json'=>$this->json(array('artifact_file_name'=>$file,'artifact_sha256'=>$sha,'record_count'=>count($records))),'error_message'=>NULL));$this->db->trans_complete();if(!$this->db->trans_status())throw new Exception('Export metadata could not be saved.');return array('message'=>'Exported '.$file,'path'=>$path,'sha256'=>$sha,'records'=>count($records));}catch(Exception$e){if($path&&is_file($path))unlink($path);$this->db->where('ml_job_id',$job->ml_job_id)->update('ml_job',array('job_status'=>'FAILED','completed_at'=>date('Y-m-d H:i:s'),'error_message'=>mb_substr($e->getMessage(),0,2000)));return array('error'=>$e->getMessage());}
	}

	private function source_rows($capability,$cutoff){if($capability==='EXTRACTION')return$this->extraction_rows($cutoff);if($capability==='MAPPING')return$this->mapping_rows($cutoff);return$this->resource_rows($cutoff);}
	private function extraction_rows($cutoff)
	{
		$rows=$this->db->select('s.*,b.boq_id,b.file_sha256,b.original_file_name')->from('boq_import_staging s')->join('boq_import_batch b','b.boq_import_batch_id=s.boq_import_batch_id')->where_in('s.validation_status',array('VALID','IMPORTED'))->where('b.uploaded_at <=',$cutoff)->order_by('s.boq_import_staging_id')->get()->result();$out=array();foreach($rows as$r){$payload=array('file_sha256'=>$r->file_sha256,'file_name'=>$r->original_file_name,'sheet'=>$r->source_sheet,'row_no'=>(int)$r->source_row_no,'raw_row'=>json_decode($r->raw_row_data,TRUE));$label=array('row_role'=>'ITEM','item_reference'=>$r->item_reference,'section_reference'=>$r->section_reference,'item_description'=>$r->item_description,'source_uom_text'=>$r->source_uom_text,'matched_uom_id'=>$r->matched_uom_id?(int)$r->matched_uom_id:NULL,'quantity'=>$r->quantity!==NULL?(float)$r->quantity:NULL,'unit_rate'=>$r->unit_rate!==NULL?(float)$r->unit_rate:NULL,'line_amount'=>$r->line_amount!==NULL?(float)$r->line_amount:NULL);$out[]=$this->record('EXTRACTION_ROW','staging:'.$r->boq_import_staging_id,'import_batch:'.$r->boq_import_batch_id,$payload,$label,array('boq_import_batch_id'=>(int)$r->boq_import_batch_id,'boq_import_staging_id'=>(int)$r->boq_import_staging_id));}return$out;
	}
	private function mapping_rows($cutoff)
	{
		$rows=$this->db->select('m.boq_item_mapping_id,m.mapping_status,m.mapping_method,m.mapped_at,bi.boq_item_id,bi.item_description,bi.quantity,bi.uom_id,bi.unit_rate,bi.line_amount,c.cost_item_revision_id,r.cost_item_id,r.standard_item_name,r.standard_description,r.uom_id target_uom_id')->from('boq_item_mapping m')->join('boq_mapping_candidate c','c.boq_mapping_candidate_id=m.boq_mapping_candidate_id')->join('boq_item bi','bi.boq_item_id=m.boq_item_id')->join('standard_cost_item_revision r','r.cost_item_revision_id=c.cost_item_revision_id')->where_in('m.mapping_status',array('CONFIRMED','REJECTED'))->where('m.mapped_at <=',$cutoff)->order_by('m.boq_item_mapping_id')->get()->result();$out=array();foreach($rows as$r){$payload=array('boq_item_id'=>(int)$r->boq_item_id,'description'=>$r->item_description,'quantity'=>$r->quantity!==NULL?(float)$r->quantity:NULL,'uom_id'=>$r->uom_id?(int)$r->uom_id:NULL,'unit_rate'=>$r->unit_rate!==NULL?(float)$r->unit_rate:NULL,'line_amount'=>$r->line_amount!==NULL?(float)$r->line_amount:NULL,'candidate_revision_id'=>(int)$r->cost_item_revision_id,'candidate_name'=>$r->standard_item_name,'candidate_description'=>$r->standard_description,'candidate_uom_id'=>$r->target_uom_id?(int)$r->target_uom_id:NULL);$label=array('polarity'=>$r->mapping_status==='CONFIRMED'?'POSITIVE':'HARD_NEGATIVE','stable_cost_item_id'=>(int)$r->cost_item_id,'mapping_status'=>$r->mapping_status,'mapping_method'=>$r->mapping_method);$out[]=$this->record('MAPPING_LABEL','mapping:'.$r->boq_item_mapping_id,'boq_item:'.$r->boq_item_id,$payload,$label,array('boq_item_mapping_id'=>(int)$r->boq_item_mapping_id,'cost_item_revision_id'=>(int)$r->cost_item_revision_id));}return$out;
	}
	private function resource_rows($cutoff)
	{
		$rows=$this->db->select('r.*,i.cost_item_uid')->from('standard_cost_item_revision r')->join('standard_cost_item i','i.cost_item_id=r.cost_item_id')->where_in('r.revision_status',array('APPROVED','PUBLISHED'))->where('r.created_at <=',$cutoff)->order_by('r.cost_item_revision_id')->get()->result();
		$out=array();
		foreach($rows as$r){
			$materials=$this->db->select('material_id,material_variant_id,quantity_per_item_unit,uom_id,waste_percentage,is_primary')->where('cost_item_revision_id',$r->cost_item_revision_id)->get('cost_item_material')->result_array();
			$labor=$this->db->select('labor_id,crew_quantity,labor_days_per_item_unit,labor_hours_per_unit')->where('cost_item_revision_id',$r->cost_item_revision_id)->get('cost_item_labor')->result_array();
			$equipment=$this->db->select('equipment_id,equipment_quantity,equipment_hours_per_unit')->where('cost_item_revision_id',$r->cost_item_revision_id)->get('cost_item_equipment')->result_array();
			$allowances=$this->db->select('resource_allowance_type_id,amount_per_item_unit')->where('cost_item_revision_id',$r->cost_item_revision_id)->get('cost_item_resource_allowance')->result_array();
			$payload=array('cost_item_uid'=>$r->cost_item_uid,'name'=>$r->standard_item_name,'description'=>$r->standard_description,'project_type_id'=>(int)$r->project_type_id,'market_segment_id'=>(int)$r->market_segment_id,'division_id'=>$r->division_id?(int)$r->division_id:NULL,'trade_id'=>$r->trade_id?(int)$r->trade_id:NULL,'uom_id'=>$r->uom_id?(int)$r->uom_id:NULL);
			$label=array('materials'=>$materials,'labor'=>$labor,'equipment'=>$equipment,'allowances'=>$allowances);
			$out[]=$this->record('RESOURCE_TEMPLATE','revision:'.$r->cost_item_revision_id,'cost_item:'.$r->cost_item_id,$payload,$label,array('cost_item_revision_id'=>(int)$r->cost_item_revision_id));
		}
		return$out;
	}
	private function record($type,$identity,$group,array$payload,array$label,array$ids){$payload_json=$this->json($payload);$label_json=$this->json($label);return array_merge(array('record_type'=>$type,'source_identity'=>$identity,'split_group_key'=>$group,'payload_json'=>$payload_json,'label_json'=>$label_json,'label_status'=>'PENDING','record_sha256'=>hash('sha256',$type."\n".$identity."\n".$group."\n".$payload_json."\n".$label_json)),$ids);}
	private function json($value){return json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION);}
}
