<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Standard_cost_item_assembly_model extends CI_Model
{
	public function options()
	{
		return array(
			'variants' => $this->db->select("v.material_variant_id option_id,v.material_id,v.uom_id,CONCAT(m.material_code,' — ',m.material_name,' / ',v.material_variant_code,IF(v.size_description IS NULL,'',CONCAT(' ',v.size_description))) option_label,rh.unit_rate,rs.currency_code", FALSE)->from('material_variant v')->join('material_master m','m.material_id=v.material_id')->join('material_rate_history rh','rh.material_rate_history_id=(SELECT rh2.material_rate_history_id FROM material_rate_history rh2 WHERE rh2.material_variant_id=v.material_variant_id AND rh2.is_current=1 ORDER BY rh2.created_at DESC,rh2.material_rate_history_id DESC LIMIT 1)','left')->join('material_rate_schedule rs','rs.material_rate_schedule_id=rh.material_rate_schedule_id','left')->where('m.is_active',1)->where('v.is_active',1)->order_by('m.material_code')->get()->result(),
			'labor' => $this->db->select("l.labor_id option_id,CONCAT(l.labor_code,' — ',l.labor_name) option_label,rh.total_with_admin_fee,rs.currency_code", FALSE)->from('labor_master l')->join('labor_rate_history rh','rh.labor_rate_history_id=(SELECT rh2.labor_rate_history_id FROM labor_rate_history rh2 WHERE rh2.labor_id=l.labor_id AND rh2.is_current=1 ORDER BY rh2.created_at DESC,rh2.labor_rate_history_id DESC LIMIT 1)','left')->join('labor_rate_schedule rs','rs.labor_rate_schedule_id=rh.labor_rate_schedule_id','left')->where('l.is_active',1)->order_by('l.labor_code')->get()->result(),
			'equipment' => $this->simple_options('equipment_master','equipment_id',"CONCAT(equipment_code,' — ',equipment_name)",'is_active=1'),
			'crews' => $this->db->select("c.crew_id option_id,CONCAT(c.crew_code,' — ',COALESCE(c.crew_name,c.source_trade),' (',COUNT(m.crew_member_id),' members)') option_label",FALSE)->from('crew_master c')->join('crew_member m','m.crew_id=c.crew_id','left')->where('c.is_active',1)->group_by('c.crew_id')->having('COUNT(m.crew_member_id) >',0)->order_by('c.crew_code')->get()->result(),
			'allowances' => $this->simple_options('ref_resource_allowance_type','resource_allowance_type_id',"CONCAT(allowance_type_code,' — ',allowance_type_name)"),
		);
	}

	public function normalize_resources(array $post, $item_uom_id)
	{
		$result=array('error'=>NULL,'materials'=>array(),'labor'=>array(),'equipment'=>array(),'allowances'=>array(),'productivity'=>NULL,'crew_members'=>array(),'currency'=>NULL,'totals'=>array('material'=>0.0,'labor'=>0.0,'allowances'=>0.0,'final'=>0.0),'warnings'=>array());$currencies=array();
		$seen=array();
		foreach($this->rows($post,'material_variant_id') as $row){
			$id=(int)$row['material_variant_id'];$qty=(float)$row['material_quantity'];$waste=(float)$row['material_waste'];
			$v=$this->db->select('v.material_variant_id,v.material_id,v.uom_id,rh.unit_rate,rs.currency_code,(SELECT COUNT(*) FROM material_rate_history rc WHERE rc.material_variant_id=v.material_variant_id AND rc.is_current=1) current_rate_count',FALSE)->from('material_variant v')->join('material_master m','m.material_id=v.material_id')->join('material_rate_history rh','rh.material_rate_history_id=(SELECT rh2.material_rate_history_id FROM material_rate_history rh2 WHERE rh2.material_variant_id=v.material_variant_id AND rh2.is_current=1 ORDER BY rh2.created_at DESC,rh2.material_rate_history_id DESC LIMIT 1)','left')->join('material_rate_schedule rs','rs.material_rate_schedule_id=rh.material_rate_schedule_id','left')->where('v.material_variant_id',$id)->where('m.is_active',1)->where('v.is_active',1)->get()->row();
			if(!$v){$result['error']='A selected material variant is invalid or inactive.';return$result;}if((int)$v->current_rate_count>1){$result['error']='A selected material variant has multiple current rates. Resolve its rate history before assembly.';return$result;}if($qty<=0){$result['error']='Every material quantity must be greater than zero.';return$result;}if($waste<0){$result['error']='Material waste percentage cannot be negative.';return$result;}
			if(isset($seen[$v->material_id])){$result['error']='A material master item can only appear once in the build-up.';return$result;}$seen[$v->material_id]=TRUE;
			$result['materials'][]=array('material_id'=>(int)$v->material_id,'material_variant_id'=>$id,'quantity_per_item_unit'=>$qty,'uom_id'=>(int)$v->uom_id,'waste_percentage'=>$waste,'is_primary'=>!empty($row['material_primary'])?1:0,'notes'=>$this->text($row['material_notes'],500));
			if($v->unit_rate===NULL)$result['warnings'][]='A selected material has no current governed rate and will be excluded from the calculated total.';else{$result['totals']['material']+=$qty*(float)$v->unit_rate;if($v->currency_code)$currencies[$v->currency_code]=TRUE;}
		}
		if(!$result['materials']){$result['error']='Add at least one material component.';return$result;}
		$primary_count=0;foreach($result['materials']as$m)$primary_count+=(int)$m['is_primary'];if($primary_count!==1){$result['error']='Select exactly one primary material.';return$result;}

		$mode=isset($post['labor_mode'])&&$post['labor_mode']==='CREW_DERIVED'?'CREW_DERIVED':'MANUAL';
		if($mode==='MANUAL'){
			$seen=array();foreach($this->rows($post,'labor_id') as$row){$id=(int)$row['labor_id'];$crew=(float)$row['labor_crew_quantity'];$days=(float)$row['labor_days'];$hours=(float)$row['labor_hours'];$labor=$this->db->select('l.labor_id,rh.total_with_admin_fee,rs.currency_code,(SELECT COUNT(*) FROM labor_rate_history rc WHERE rc.labor_id=l.labor_id AND rc.is_current=1) current_rate_count',FALSE)->from('labor_master l')->join('labor_rate_history rh','rh.labor_rate_history_id=(SELECT rh2.labor_rate_history_id FROM labor_rate_history rh2 WHERE rh2.labor_id=l.labor_id AND rh2.is_current=1 ORDER BY rh2.created_at DESC,rh2.labor_rate_history_id DESC LIMIT 1)','left')->join('labor_rate_schedule rs','rs.labor_rate_schedule_id=rh.labor_rate_schedule_id','left')->where('l.labor_id',$id)->where('l.is_active',1)->get()->row();if(!$labor||$crew<=0||$days<=0||$hours<0){$result['error']='Every manual labor row requires an active craft, positive crew quantity, positive days per item unit, and non-negative hours.';return$result;}if((int)$labor->current_rate_count>1){$result['error']='A selected labor craft has multiple current rates. Resolve its rate history before assembly.';return$result;}if(isset($seen[$id])){$result['error']='A labor craft can only appear once in the build-up.';return$result;}$seen[$id]=TRUE;$result['labor'][]=array('labor_id'=>$id,'crew_quantity'=>$crew,'labor_days_per_item_unit'=>$days,'labor_hours_per_unit'=>$hours,'notes'=>$this->text($row['labor_notes'],500));if($labor->total_with_admin_fee===NULL)$result['warnings'][]='A selected labor craft has no current governed rate and will be excluded from the calculated total.';else{$result['totals']['labor']+=$days*(float)$labor->total_with_admin_fee;if($labor->currency_code)$currencies[$labor->currency_code]=TRUE;}}
			if(!$result['labor']){$result['error']='Add at least one manual labor component or select Crew Derived labor.';return$result;}
		}else{
			$crew_id=(int)($post['crew_id']??0);$output=(float)($post['crew_output_quantity']??0);$duration=(float)($post['crew_duration_days']??0);$source=$this->text($post['crew_productivity_source']??'',100);$reference=$this->text($post['crew_source_reference']??'',255);$effective=trim((string)($post['crew_effective_date']??''));
			$crew=$this->db->where('crew_id',$crew_id)->where('is_active',1)->get('crew_master')->row();$day=$this->db->where('LOWER(uom_code)','d')->where('is_active',1)->get('ref_uom')->row();
			$date=DateTime::createFromFormat('!Y-m-d',$effective);if(!$crew||!$day||$output<=0||$duration<=0||!$source||!$reference||!$date||$date->format('Y-m-d')!==$effective){$result['error']='Crew Derived labor requires an active crew, positive output and duration in days, source, reference, and valid effective date.';return$result;}
			$members=$this->db->select('m.crew_member_id,m.labor_id,m.member_count,l.labor_code,l.is_active,rh.total_with_admin_fee,rs.currency_code,(SELECT COUNT(*) FROM labor_rate_history rc WHERE rc.labor_id=m.labor_id AND rc.is_current=1) current_rate_count',FALSE)->from('crew_member m')->join('labor_master l','l.labor_id=m.labor_id')->join('labor_rate_history rh','rh.labor_rate_history_id=(SELECT rh2.labor_rate_history_id FROM labor_rate_history rh2 WHERE rh2.labor_id=m.labor_id AND rh2.is_current=1 ORDER BY rh2.created_at DESC,rh2.labor_rate_history_id DESC LIMIT 1)','left')->join('labor_rate_schedule rs','rs.labor_rate_schedule_id=rh.labor_rate_schedule_id','left')->where('m.crew_id',$crew_id)->get()->result();
			if(!$members){$result['error']='The selected crew has no labor members.';return$result;}$currency=NULL;
			foreach($members as$m){if(!$m->is_active||$m->total_with_admin_fee===NULL){$result['error']='Every selected crew member must be active and have a current governed labor rate.';return$result;}if((int)$m->current_rate_count>1){$result['error']='A selected crew member labor craft has multiple current rates. Resolve its rate history before assembly.';return$result;}if($currency===NULL)$currency=$m->currency_code;elseif($currency!==$m->currency_code){$result['error']='Selected crew member rates use mixed currencies.';return$result;}$days=(float)$m->member_count*$duration/$output;$result['crew_members'][]=array('crew_member_id'=>(int)$m->crew_member_id,'labor_id'=>(int)$m->labor_id,'member_count'=>(float)$m->member_count,'labor_days'=>$days,'rate'=>(float)$m->total_with_admin_fee,'currency'=>$m->currency_code);$result['labor'][]=array('labor_id'=>(int)$m->labor_id,'crew_quantity'=>(float)$m->member_count,'labor_days_per_item_unit'=>$days,'labor_hours_per_unit'=>0.0,'notes'=>'Crew-derived during guided Draft assembly');$result['totals']['labor']+=$days*(float)$m->total_with_admin_fee;}if($currency)$currencies[$currency]=TRUE;
			$result['productivity']=array('output_quantity'=>$output,'output_uom_id'=>(int)$item_uom_id,'duration_quantity'=>$duration,'duration_uom_id'=>(int)$day->uom_id,'crew_id'=>$crew_id,'duration_hours'=>NULL,'crew_description'=>NULL,'productivity_source'=>$source,'source_reference'=>$reference,'effective_date'=>$effective,'is_benchmark'=>!empty($post['crew_is_benchmark'])?1:0,'notes'=>$this->text($post['crew_notes']??'',500));
		}

		$seen=array();foreach($this->rows($post,'equipment_id')as$row){$id=(int)$row['equipment_id'];$qty=(float)$row['equipment_quantity'];$hours=(float)$row['equipment_hours'];if(!$this->exists('equipment_master','equipment_id',$id,'is_active=1')||$qty<=0||$hours<0){$result['error']='Every equipment row requires an active equipment item, positive quantity, and non-negative hours.';return$result;}if(isset($seen[$id])){$result['error']='An equipment item can only appear once.';return$result;}$seen[$id]=TRUE;$result['equipment'][]=array('equipment_id'=>$id,'equipment_quantity'=>$qty,'equipment_hours_per_unit'=>$hours,'notes'=>$this->text($row['equipment_notes'],500));}
		if($result['equipment'])$result['warnings'][]='Equipment is recorded but excluded from Final Unit Rate because no governed equipment-rate structure exists.';
		$seen=array();foreach($this->rows($post,'allowance_type_id')as$row){$id=(int)$row['allowance_type_id'];$amount=(float)$row['allowance_amount'];if($amount<0||!$this->exists('ref_resource_allowance_type','resource_allowance_type_id',$id)){$result['error']='Allowance amounts must be non-negative and use governed allowance types.';return$result;}if($amount==0.0)continue;if(isset($seen[$id])){$result['error']='An allowance type can only appear once.';return$result;}$seen[$id]=TRUE;$result['allowances'][]=array('resource_allowance_type_id'=>$id,'amount_per_item_unit'=>$amount,'notes'=>$this->text($row['allowance_notes'],500));$result['totals']['allowances']+=$amount;}
		if(count($currencies)>1){$result['error']='Current material and labor rates use mixed currencies and cannot be reconciled into one Final Unit Rate.';return$result;}$result['currency']=$currencies?key($currencies):NULL;
		$result['totals']['final']=$result['totals']['material']+$result['totals']['labor']+$result['totals']['allowances'];$result['labor_mode']=$mode;$result['warnings']=array_values(array_unique($result['warnings']));return$result;
	}

	public function create_draft(array $revision,array $resources,$actor)
	{
		$locked=FALSE;$this->db->trans_begin();
		try{$lock=$this->db->query("SELECT GET_LOCK('nexus_ucd_standard_cost_item_sequence',10) acquired")->row();if(!$lock||(int)$lock->acquired!==1)throw new Exception('Unable to reserve a Standard Cost Item sequence.');$locked=TRUE;$row=$this->db->select_max('item_sequence','max_sequence')->get('standard_cost_item')->row();$sequence=(int)($row->max_sequence??0)+1;$uid='UCD-'.str_pad((string)$sequence,6,'0',STR_PAD_LEFT);
			$this->db->insert('standard_cost_item',array('cost_item_uid'=>$uid,'item_sequence'=>$sequence,'lifecycle_status'=>'ACTIVE','created_by'=>(int)$actor));if(!$this->db->affected_rows())throw new Exception('Unable to create the Standard Cost Item.');$item_id=(int)$this->db->insert_id();
			$revision+=array('cost_item_id'=>$item_id,'revision_no'=>'01','enterprise_cost_code'=>NULL,'revision_status'=>'DRAFT','coding_status'=>'READY_FOR_CODE','supersedes_revision_id'=>NULL,'is_current'=>1,'created_by'=>(int)$actor,'approved_at'=>NULL,'approved_by'=>NULL);$this->db->insert('standard_cost_item_revision',$revision);$revision_id=(int)$this->db->insert_id();if(!$revision_id)throw new Exception('Unable to create the initial Draft revision.');
			$this->db->insert('cost_item_code_component',array('cost_item_revision_id'=>$revision_id,'division_id'=>$revision['division_id'],'section_id'=>$revision['section_id'],'uniformat_level3_id'=>$revision['uniformat_level3_id'],'uniformat_level4_id'=>$revision['uniformat_level4_id'],'specification_id'=>$revision['specification_id'],'trade_id'=>$revision['trade_id'],'item_sequence_no'=>$sequence,'revision_code'=>'01','item_segment'=>str_pad((string)$sequence,6,'0',STR_PAD_LEFT),'revision_segment'=>'01','coding_status'=>'READY_FOR_CODE','validation_message'=>'Guided Draft created; enterprise code remains subject to governed coding.'));
			foreach($resources['materials']as$row){$row['cost_item_revision_id']=$revision_id;$this->db->insert('cost_item_material',$row);}foreach($resources['equipment']as$row){$row['cost_item_revision_id']=$revision_id;$this->db->insert('cost_item_equipment',$row);}foreach($resources['allowances']as$row){$row['cost_item_revision_id']=$revision_id;$this->db->insert('cost_item_resource_allowance',$row);}
			$productivity_id=NULL;if($resources['productivity']){$p=$resources['productivity'];$p['cost_item_revision_id']=$revision_id;$this->db->insert('cost_item_productivity',$p);$productivity_id=(int)$this->db->insert_id();}
			$labor_ids=array();foreach($resources['labor']as$row){$row['cost_item_revision_id']=$revision_id;$this->db->insert('cost_item_labor',$row);$labor_ids[(int)$row['labor_id']]=(int)$this->db->insert_id();}
			$build=array('cost_item_revision_id'=>$revision_id,'labor_source_method'=>$resources['labor_mode'],'costing_productivity_id'=>$productivity_id,'crew_id'=>$resources['productivity']?(int)$resources['productivity']['crew_id']:NULL,'duration_days_snapshot'=>$resources['productivity']?(float)$resources['productivity']['duration_quantity']:NULL,'output_quantity_snapshot'=>$resources['productivity']?(float)$resources['productivity']['output_quantity']:NULL,'output_uom_id'=>$resources['productivity']?(int)$resources['productivity']['output_uom_id']:NULL,'is_stale'=>0,'applied_by'=>(int)$actor,'applied_at'=>date('Y-m-d H:i:s'));$this->db->insert('cost_item_labor_build_up',$build);
			if($resources['labor_mode']==='CREW_DERIVED')foreach($resources['crew_members']as$m)$this->db->insert('cost_item_labor_derivation',array('cost_item_revision_id'=>$revision_id,'cost_item_labor_id'=>$labor_ids[$m['labor_id']],'productivity_id'=>$productivity_id,'crew_member_id'=>$m['crew_member_id'],'labor_id'=>$m['labor_id'],'member_count_snapshot'=>$m['member_count'],'duration_days_snapshot'=>$resources['productivity']['duration_quantity'],'output_quantity_snapshot'=>$resources['productivity']['output_quantity'],'labor_days_per_item_unit_snapshot'=>$m['labor_days'],'labor_rate_snapshot'=>$m['rate'],'currency_code_snapshot'=>$m['currency'],'created_by'=>(int)$actor));
			$this->db->insert('cost_item_audit_log',array('cost_item_id'=>$item_id,'cost_item_revision_id'=>$revision_id,'event_type'=>'ITEM_CREATED','field_name'=>'revision_status','old_value'=>NULL,'new_value'=>'DRAFT','changed_by'=>(int)$actor,'source_application'=>'Project Nexus UCD Web','source_reference'=>'Guided Draft Assembly'));
			if($this->db->trans_status()===FALSE)throw new Exception('The Draft could not be saved atomically.');$this->db->trans_commit();return array('cost_item_id'=>$item_id,'uid'=>$uid);
		}catch(Exception$e){$this->db->trans_rollback();return array('error'=>$e->getMessage());}finally{if($locked)$this->db->query("SELECT RELEASE_LOCK('nexus_ucd_standard_cost_item_sequence')");}
	}

	private function rows(array$post,$key){$values=isset($post[$key])&&is_array($post[$key])?$post[$key]:array();$map=array('material_variant_id'=>array('material_quantity','material_waste','material_primary','material_notes'),'labor_id'=>array('labor_crew_quantity','labor_days','labor_hours','labor_notes'),'equipment_id'=>array('equipment_quantity','equipment_hours','equipment_notes'),'allowance_type_id'=>array('allowance_amount','allowance_notes'));$rows=array();foreach($values as$i=>$value){if(trim((string)$value)==='')continue;$row=array($key=>$value);foreach($map[$key]as$field)$row[$field]=isset($post[$field][$i])?$post[$field][$i]:'';$rows[]=$row;}return$rows;}
	private function text($value,$max){$value=trim((string)$value);return$value===''?NULL:mb_substr($value,0,$max);}
	private function exists($table,$key,$id,$where=NULL){$this->db->where($key,(int)$id);if($where)$this->db->where($where,NULL,FALSE);return$this->db->count_all_results($table)>0;}
	private function simple_options($table,$key,$label,$where=NULL){$this->db->select($key.' option_id,'.$label.' option_label',FALSE);if($where)$this->db->where($where,NULL,FALSE);return$this->db->order_by('option_label')->get($table)->result();}
}
