<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="row justify-content-center"><div class="col-xl-9"><div class="card shadow-sm"><div class="card-header"><h2 class="card-title mb-0"><?= html_escape($page_title) ?></h2></div><div class="card-body">
	<?php if ($form_error): ?><div class="alert alert-danger" role="alert"><?= html_escape($form_error) ?></div><?php endif; ?><?= validation_errors('<div class="alert alert-danger" role="alert">', '</div>') ?>
	<?= form_open(current_url(), array('novalidate' => 'novalidate')) ?><div class="row g-3">
		<div class="col-md-4"><label class="form-label" for="equipment_code">Equipment code *</label><input class="form-control text-uppercase" id="equipment_code" name="equipment_code" maxlength="50" value="<?= set_value('equipment_code', $equipment->equipment_code ?? '') ?>" required></div>
		<div class="col-md-8"><label class="form-label" for="equipment_name">Equipment name *</label><input class="form-control" id="equipment_name" name="equipment_name" maxlength="200" value="<?= set_value('equipment_name', $equipment->equipment_name ?? '') ?>" required></div>
		<div class="col-md-6"><label class="form-label" for="equipment_group_id">Equipment group *</label><select class="form-select" id="equipment_group_id" name="equipment_group_id" required><option value="">Select…</option><?php foreach ($groups as $option): ?><option value="<?= (int) $option->option_id ?>" <?= set_select('equipment_group_id', (string) $option->option_id, (string) set_value('equipment_group_id', $equipment->equipment_group_id ?? '') === (string) $option->option_id) ?>><?= html_escape($option->option_label) ?></option><?php endforeach; ?></select></div>
		<div class="col-md-3"><label class="form-label" for="equipment_scope">Scope *</label><input class="form-control text-uppercase" id="equipment_scope" name="equipment_scope" maxlength="30" value="<?= set_value('equipment_scope', $equipment->equipment_scope ?? '') ?>" required><div class="form-text">For example, GENERIC_TYPE.</div></div>
		<div class="col-md-3"><label class="form-label" for="equipment_category">Category</label><input class="form-control" id="equipment_category" name="equipment_category" maxlength="100" value="<?= set_value('equipment_category', $equipment->equipment_category ?? '') ?>"></div>
	</div>
	<?php $active_default = $this->input->method(TRUE) !== 'POST' && ($equipment === NULL || (bool) $equipment->is_active); ?><div class="form-check my-4"><input class="form-check-input" type="checkbox" id="is_active" name="is_active" value="1" <?= set_checkbox('is_active', '1', $active_default) ?>><label class="form-check-label" for="is_active">Active</label></div>
	<?php if ($equipment): ?><p class="small text-body-secondary">Created <?= html_escape(date('d-M-Y h:i A', strtotime($equipment->created_at))) ?> · Updated <?= html_escape(date('d-M-Y h:i A', strtotime($equipment->updated_at))) ?></p><?php endif; ?>
	<button class="btn btn-primary" type="submit">Save Equipment</button> <a class="btn btn-outline-secondary" href="<?= $equipment ? site_url('equipment/'.$equipment->equipment_id) : site_url('equipment') ?>">Cancel</a><?= form_close() ?>
</div></div></div></div>
