<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<?php $select=function($name,$label,$rows)use($filters){?><div class="col-md-4 col-xl-3"><label class="form-label" for="<?=$name?>"><?=html_escape($label)?></label><select class="form-select" id="<?=$name?>" name="<?=$name?>"><option value="">All</option><?php foreach($rows as$row):?><option value="<?=html_escape($row->option_id)?>" <?=(string)$filters[$name]===(string)$row->option_id?'selected':''?>><?=html_escape($row->option_label)?></option><?php endforeach;?></select></div><?php }; ?>
<?php if($filter_error):?><div class="alert alert-danger" role="alert"><?=html_escape($filter_error)?></div><?php endif;?>
<div class="card shadow-sm mb-4"><div class="card-header"><h2 class="card-title mb-0">Benchmark Filters</h2></div><div class="card-body"><form method="get" action="<?=site_url('benchmarking')?>"><div class="row g-3">
<div class="col-md-4 col-xl-3"><label class="form-label" for="group_by">Compare by</label><select class="form-select" id="group_by" name="group_by"><?php foreach($dimensions as$key=>$definition):?><option value="<?=html_escape($key)?>" <?=$filters['group_by']===$key?'selected':''?>><?=html_escape($definition['label'])?></option><?php endforeach;?></select></div>
<?php $select('cost_item_id','Cost item',$options['cost_items']);$select('project_id','Project',$options['projects']);$select('location_id','Location',$options['locations']);$select('division_id','CSI division',$options['divisions']);$select('trade_id','Trade',$options['trades']);$select('uom_id','Unit of measure',$options['uoms']);$select('contractor','Contractor / vendor',$options['contractors']); ?>
<div class="col-md-4 col-xl-3"><label class="form-label" for="date_from">Rate date from</label><input class="form-control" type="date" id="date_from" name="date_from" value="<?=html_escape($filters['date_from'])?>"></div><div class="col-md-4 col-xl-3"><label class="form-label" for="date_to">Rate date to</label><input class="form-control" type="date" id="date_to" name="date_to" value="<?=html_escape($filters['date_to'])?>"></div>
<div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" id="validated_only" name="validated_only" value="1" <?=$filters['validated_only']?'checked':''?>><label class="form-check-label" for="validated_only">Validated observations only</label></div></div>
</div><div class="mt-3"><button class="btn btn-primary" type="submit">Apply Benchmark</button> <a class="btn btn-outline-secondary" href="<?=site_url('benchmarking')?>">Reset</a></div></form></div></div>

<div class="row g-3 mb-4"><div class="col-md-6 col-xl-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-body-secondary">Observations</div><div class="display-6 fw-semibold"><?=number_format($summary->count)?></div></div></div></div><div class="col-md-6 col-xl-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-body-secondary"><?=html_escape($dimension['label'])?> Groups</div><div class="display-6 fw-semibold"><?=number_format(count($groups))?></div></div></div></div><div class="col-md-6 col-xl-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-body-secondary">Projects / Locations</div><div class="display-6 fw-semibold"><?=number_format($summary->project_count)?> / <?=number_format($summary->location_count)?></div></div></div></div><div class="col-md-6 col-xl-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-body-secondary">Dated / Validated</div><div class="display-6 fw-semibold"><?=number_format($summary->dated_count)?> / <?=number_format($summary->validated_count)?></div></div></div></div></div>

<?php if($summary->count&&($summary->project_count===0||$summary->dated_count===0||$summary->validated_count===0)):?><div class="alert alert-warning"><strong>Coverage limitation:</strong> the current historical data is primarily reference baseline data. Project, location, period, contractor, currency, and validation comparisons will populate as governed observations are appended. Statistics are always separated by UOM and currency.</div><?php endif;?>

<?php if($chart_enabled&&$groups):?><div class="card shadow-sm mb-4"><div class="card-header"><h2 class="card-title mb-0">Average Rate by <?=html_escape($dimension['label'])?></h2></div><div class="card-body"><div style="height:<?=max(300,min(700,count($groups)*38))?>px"><canvas id="benchmark-chart" data-labels="<?=html_escape(json_encode($chart_labels,JSON_UNESCAPED_UNICODE))?>" data-values="<?=html_escape(json_encode($chart_values))?>"></canvas></div></div></div><?php elseif($groups):?><div class="alert alert-info">Select one UOM before charting rates. Aggregating unlike units into one chart would be misleading.</div><?php endif;?>

<div class="card shadow-sm mb-4"><div class="card-header"><h2 class="card-title mb-0"><?=html_escape($dimension['label'])?> Comparison</h2></div><div class="card-body"><div class="table-responsive"><table class="table table-striped table-hover align-middle benchmark-table"><thead><tr><th><?=html_escape($dimension['label'])?></th><th>UOM</th><th>Currency</th><th>Observations</th><th>Minimum</th><th>P25</th><th>Median</th><th>Average</th><th>P75</th><th>Maximum</th><th>Projects</th><th>Locations</th><th>Contractors</th><th>Date Range</th></tr></thead><tbody><?php foreach($groups as$group):?><tr><td><?=html_escape($group->label)?></td><td><?=html_escape($group->uom)?></td><td><?=html_escape($group->currency)?></td><td><?=number_format($group->count)?></td><td><?=number_format($group->minimum,2)?></td><td><?=number_format($group->p25,2)?></td><td><?=number_format($group->median,2)?></td><td><?=number_format($group->average,2)?></td><td><?=number_format($group->p75,2)?></td><td><?=number_format($group->maximum,2)?></td><td><?=number_format($group->project_count)?></td><td><?=number_format($group->location_count)?></td><td><?=number_format($group->contractor_count)?></td><td><?=$group->first_date?html_escape(date('d-M-Y',strtotime($group->first_date)).' — '.date('d-M-Y',strtotime($group->last_date))):'Not recorded'?></td></tr><?php endforeach;?></tbody></table></div><?php if(!$groups):?><p class="text-body-secondary mb-0">No rate observations match the selected filters.</p><?php endif;?></div></div>

<div class="card shadow-sm"><div class="card-header"><h2 class="card-title mb-0">Underlying Historical Observations</h2></div><div class="card-body"><div class="table-responsive"><table class="table table-striped table-hover align-middle benchmark-table"><thead><tr><th>Cost Item</th><th>Project</th><th>Location</th><th>Period</th><th>Contractor</th><th>Classification</th><th>UOM</th><th>Unit Rate</th><th>Currency</th><th>Rate Type</th><th>Validation</th></tr></thead><tbody><?php foreach($observations as$row):?><tr><td><a href="<?=site_url('standard-cost-items/'.$row->cost_item_id)?>"><?=html_escape($row->enterprise_cost_code?:$row->cost_item_uid)?></a><div class="small text-body-secondary"><?=html_escape($row->standard_item_name)?></div></td><td><?=html_escape($row->project_code?:'Not recorded')?></td><td><?=html_escape($row->location_name?:'Not recorded')?></td><td><?=html_escape($row->period_label?:($row->rate_date?date('Y',strtotime($row->rate_date)):'Not recorded'))?></td><td><?=html_escape($row->contractor_supplier?:'Not recorded')?></td><td><?=html_escape(trim(($row->division_code?:'').' / '.($row->trade_code?:''),' /')?:'Not recorded')?></td><td><?=html_escape($row->uom_code?:'Not recorded')?></td><td><?=number_format($row->unit_rate,2)?></td><td><?=html_escape($row->currency_code?:'Not recorded')?></td><td><?=html_escape($row->rate_type?:'Not recorded')?></td><td><?=html_escape($row->validation_status?:'Not recorded')?></td></tr><?php endforeach;?></tbody></table></div></div></div>
