<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="d-flex justify-content-end mb-4"><a class="btn btn-primary" href="<?=site_url('cost-intelligence/suggestions')?>">Review Mapping Suggestions</a></div>

<div class="row g-3 mb-4">
	<div class="col-md-6 col-xl-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-body-secondary">Rate Observations</div><div class="display-6 fw-semibold"><?=number_format((int)$coverage->observation_count)?></div></div></div></div>
	<div class="col-md-6 col-xl-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-body-secondary">Range Groups</div><div class="display-6 fw-semibold"><?=number_format(count($ranges))?></div></div></div></div>
	<div class="col-md-6 col-xl-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-body-secondary">Outlier Signals</div><div class="display-6 fw-semibold"><?=number_format(count($outliers))?></div></div></div></div>
	<div class="col-md-6 col-xl-3"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-body-secondary">Dated Trend Groups</div><div class="display-6 fw-semibold"><?=number_format(count($trends))?></div></div></div></div>
</div>

<?php if((int)$coverage->project_count===0||(int)$coverage->location_count===0||(int)$coverage->dated_count===0||(int)$coverage->validated_count===0):?>
<div class="alert alert-warning" role="alert"><strong>Evidence limitation:</strong> current rate history lacks sufficient project, location, dated, or validated context. Range signals remain provisional and must be reviewed by a cost professional. They do not update governed master data.</div>
<?php endif;?>

<div class="card shadow-sm mb-4"><div class="card-header"><h2 class="card-title mb-0">Benchmark Range Signals</h2></div><div class="card-body"><p class="small text-body-secondary">Each group contains at least five comparable observations and is separated by classification, UOM, and currency. The middle 50% (P25–P75) is the proposed range; confidence determines whether it is recommendable.</p><div class="table-responsive"><table class="table table-striped table-hover align-middle intelligence-table"><thead><tr><th>Classification</th><th>UOM</th><th>Currency</th><th>Sample</th><th>P25</th><th>Median</th><th>P75</th><th>Outliers</th><th>Confidence</th><th>Status</th></tr></thead><tbody><?php foreach($ranges as$range):?><?php $recommendable=!empty($range->confidence->is_recommendable);?><tr><td><?=html_escape($range->label)?></td><td><?=html_escape($range->uom)?></td><td><?=html_escape($range->currency)?></td><td><?=number_format($range->sample_count)?></td><td><?=number_format($range->p25,2)?></td><td><?=number_format($range->median,2)?></td><td><?=number_format($range->p75,2)?></td><td><?=number_format($range->outlier_count)?></td><td><span class="badge text-bg-<?=$recommendable?'success':'secondary'?>"><?=html_escape($range->confidence->confidence_name)?> · <?=number_format($range->confidence_score,2)?></span><div class="small text-body-secondary mt-1"><?=html_escape($range->confidence_basis)?></div></td><td><?=$recommendable?'<span class="badge text-bg-success">Recommendable</span>':'<span class="badge text-bg-warning">Review required</span>'?></td></tr><?php endforeach;?></tbody></table></div><?php if(!$ranges):?><p class="text-body-secondary mb-0">No groups currently meet the minimum sample requirement.</p><?php endif;?></div></div>

<div class="card shadow-sm mb-4"><div class="card-header"><h2 class="card-title mb-0">Abnormal Rate Signals</h2></div><div class="card-body"><p class="small text-body-secondary">A value is flagged when it falls outside 1.5 × IQR below P25 or above P75. A signal is evidence for review, not a finding of error.</p><div class="table-responsive"><table class="table table-striped table-hover align-middle intelligence-table"><thead><tr><th>Standard Item</th><th>Classification</th><th>UOM</th><th>Rate</th><th>Expected Fence</th><th>Direction</th><th>Median Deviation</th><th>Validation</th></tr></thead><tbody><?php foreach($outliers as$row):?><tr><td><a href="<?=site_url('standard-cost-items/'.$row->cost_item_id)?>"><?=html_escape($row->enterprise_cost_code?:$row->cost_item_uid)?></a><div class="small text-body-secondary"><?=html_escape($row->standard_item_name)?></div></td><td><?=html_escape($row->group_label)?></td><td><?=html_escape($row->uom_code?:'Not recorded')?></td><td><?=number_format($row->unit_rate,2)?></td><td><?=number_format($row->lower_bound,2)?> – <?=number_format($row->upper_bound,2)?></td><td><span class="badge text-bg-warning"><?=html_escape($row->direction)?></span></td><td><?=number_format($row->deviation_percent,2)?>%</td><td><?=html_escape($row->validation_status?:($row->is_validated?'VALID':'Not recorded'))?></td></tr><?php endforeach;?></tbody></table></div><?php if(!$outliers):?><p class="text-body-secondary mb-0">No IQR outliers were detected in eligible groups.</p><?php endif;?></div></div>

<div class="card shadow-sm mb-4"><div class="card-header"><h2 class="card-title mb-0">Historical Rate Trends</h2></div><div class="card-body"><?php if($trends):?><div style="height:360px"><canvas id="trend-chart" data-labels="<?=html_escape(json_encode($trend_labels,JSON_UNESCAPED_UNICODE))?>" data-values="<?=html_escape(json_encode($trend_values))?>"></canvas></div><div class="table-responsive mt-3"><table class="table table-sm intelligence-table"><thead><tr><th>Year</th><th>Division</th><th>UOM</th><th>Sample</th><th>Average</th><th>Minimum</th><th>Maximum</th></tr></thead><tbody><?php foreach($trends as$trend):?><tr><td><?=html_escape($trend->period_year)?></td><td><?=html_escape($trend->division_code?:'Unclassified')?></td><td><?=html_escape($trend->uom_code?:'Not recorded')?></td><td><?=number_format($trend->sample_count)?></td><td><?=number_format($trend->average_rate,2)?></td><td><?=number_format($trend->minimum_rate,2)?></td><td><?=number_format($trend->maximum_rate,2)?></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="alert alert-info mb-0">No historical trend can be calculated because the current rate observations do not contain rate dates. The system will display annual trends when dated observations are available.</div><?php endif;?></div></div>

<div class="card shadow-sm"><div class="card-header"><h2 class="card-title mb-0">How These Signals Are Produced</h2></div><div class="card-body"><ul class="mb-0"><li>Mapping candidates use deterministic term overlap, phrase matching, and UOM agreement; every score includes an explanation.</li><li>Range signals use P25, median, and P75 within comparable classification/UOM/currency groups.</li><li>Confidence combines sample size, governed source and basis, validation, dated evidence, and location coverage.</li><li>All intelligence is read-only. A user must follow the governed BOQ mapping workflow to make a selection.</li></ul></div></div>
