<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="row justify-content-center"><div class="col-xl-9"><div class="card shadow-sm"><div class="card-header"><h2 class="card-title mb-0"><?= html_escape($page_title) ?></h2></div><div class="card-body">
	<?php if ($form_error): ?><div class="alert alert-danger" role="alert"><?= html_escape($form_error) ?></div><?php endif; ?><?= validation_errors('<div class="alert alert-danger" role="alert">', '</div>') ?>
	<?= form_open(current_url(), array('novalidate' => 'novalidate')) ?><div class="row g-3">
		<div class="col-md-4"><label class="form-label" for="labor_code">Labor code *</label><input class="form-control text-uppercase" id="labor_code" name="labor_code" maxlength="50" value="<?= set_value('labor_code', $labor->labor_code ?? '') ?>" required></div>
		<div class="col-md-8"><label class="form-label" for="labor_name">Labor craft name *</label><input class="form-control" id="labor_name" name="labor_name" maxlength="200" value="<?= set_value('labor_name', $labor->labor_name ?? '') ?>" required></div>
		<div class="col-md-7"><label class="form-label" for="labor_category_id">Governed category *</label><select class="form-select" id="labor_category_id" name="labor_category_id" required><option value="">Select…</option><?php foreach ($categories as $option): ?><option value="<?= (int) $option->option_id ?>" <?= set_select('labor_category_id', (string) $option->option_id, (string) set_value('labor_category_id', $labor->labor_category_id ?? '') === (string) $option->option_id) ?>><?= html_escape($option->option_label) ?></option><?php endforeach; ?></select></div>
		<div class="col-md-5"><label class="form-label" for="labor_category">Legacy category label</label><input class="form-control" id="labor_category" name="labor_category" maxlength="100" value="<?= set_value('labor_category', $labor->labor_category ?? '') ?>"><div class="form-text">Retained only for compatibility with source data.</div></div>
	</div>
	<?php $active_default = $this->input->method(TRUE) !== 'POST' && ($labor === NULL || (bool) $labor->is_active); ?><div class="form-check my-4"><input class="form-check-input" type="checkbox" id="is_active" name="is_active" value="1" <?= set_checkbox('is_active', '1', $active_default) ?>><label class="form-check-label" for="is_active">Active</label></div>
	<?php if ($labor): ?><p class="small text-body-secondary">Created <?= html_escape(date('d-M-Y h:i A', strtotime($labor->created_at))) ?> · Updated <?= html_escape(date('d-M-Y h:i A', strtotime($labor->updated_at))) ?></p><?php endif; ?>
	<button class="btn btn-primary" type="submit">Save Labor Craft</button> <a class="btn btn-outline-secondary" href="<?= $labor ? site_url('labor/'.$labor->labor_id) : site_url('labor') ?>">Cancel</a><?= form_close() ?>
</div></div></div></div>
