<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<?php $categories = array(); foreach ($labor_records as $item) if ($item->labor_category_name) $categories[$item->labor_category_name] = $item->labor_category_name; ksort($categories); ?>
<?php if ($this->session->flashdata('labor_success')): ?><div class="alert alert-success" role="alert"><?= html_escape($this->session->flashdata('labor_success')) ?></div><?php endif; ?>
<div class="card shadow-sm mb-3"><div class="card-body"><div class="row g-3 align-items-end">
	<div class="col-md-5"><label class="form-label" for="labor-category-filter">Category</label><select class="form-select" id="labor-category-filter" data-master-filter data-table-target="labor-table" data-column="2"><option value="">All categories</option><?php foreach ($categories as $value): ?><option value="<?= html_escape($value) ?>"><?= html_escape($value) ?></option><?php endforeach; ?></select></div>
	<div class="col-md-4"><label class="form-label" for="labor-status-filter">Status</label><select class="form-select" id="labor-status-filter" data-master-filter data-table-target="labor-table" data-column="7"><option value="">All statuses</option><option>Active</option><option>Inactive</option></select></div>
	<div class="col-md-3"><?php if ($can_manage): ?><a class="btn btn-primary w-100" href="<?= site_url('labor/create') ?>"><i class="bi bi-plus-lg" aria-hidden="true"></i> Add Labor Craft</a><?php endif; ?></div>
</div></div></div>
<div class="card shadow-sm"><div class="card-body"><div class="table-responsive"><table id="labor-table" class="table table-striped table-hover align-middle w-100 master-data-table"><thead><tr><th>Code</th><th>Labor Craft</th><th>Category</th><th>Daily Rate</th><th>Total Rate</th><th>Aliases</th><th>Cost Item Uses</th><th>Status</th><th data-dt-order="disable">Actions</th></tr></thead><tbody>
<?php foreach ($labor_records as $item): ?><tr><td><a class="fw-semibold text-decoration-none" href="<?= site_url('labor/'.$item->labor_id) ?>"><?= html_escape($item->labor_code) ?></a></td><td><?= html_escape($item->labor_name) ?></td><td><?= html_escape($item->labor_category_name ?? '—') ?></td><td data-order="<?= $item->current_daily_rate ?? '' ?>"><?= $item->current_daily_rate !== NULL ? html_escape(($item->currency_code ? $item->currency_code.' ' : '').number_format($item->current_daily_rate, 2)) : '—' ?></td><td data-order="<?= $item->current_total_rate ?? '' ?>"><?= $item->current_total_rate !== NULL ? html_escape(($item->currency_code ? $item->currency_code.' ' : '').number_format($item->current_total_rate, 2)) : '—' ?></td><td><?= number_format($item->alias_count) ?></td><td><?= number_format($item->usage_count) ?></td><td><span class="badge text-bg-<?= $item->is_active ? 'success' : 'secondary' ?>"><?= $item->is_active ? 'Active' : 'Inactive' ?></span></td><td class="text-nowrap"><a class="btn btn-outline-secondary btn-sm" href="<?= site_url('labor/'.$item->labor_id) ?>" aria-label="View"><i class="bi bi-eye" aria-hidden="true"></i></a><?php if ($can_manage): ?> <a class="btn btn-outline-primary btn-sm" href="<?= site_url('labor/'.$item->labor_id.'/edit') ?>" aria-label="Edit"><i class="bi bi-pencil" aria-hidden="true"></i></a><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div></div></div>
